### ISSUE TITLE
Grid loses it's items after setColumnReorderingAllowed(true)

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-grid-flow#91] opened 2018-02-14 13:21 UTC
In the Grid demo "Configuring columns", clicking the "Toggle user reordering of columns" button empties the grid.

It seems that if you call `grid.setColumnReorderingAllowed(true)` right after constructing and setting items for the grid, everything works, but if you call the method later eg. via button-click, the items are lost.

I couldn't reproduce the issue in the element-demo by setting the property with dev-tools.

**Comment by SomeoneToIgnore** [comment] 2018-03-02 15:05
The actual problem is not exactly caused by `setColumnReorderingAllowed`: it is triggered by any property synchronization, so the code`grid.getElement().setProperty("whatever", "1");` called via button click would do the same.

The reason for that is that `size` property is not synchronized, because corresponding web component does not produce event when it's changed.
We set `size` on a client side in `UpdateQueue` constructor to a proper value (https://github.com/vaadin/vaadin-grid-flow/blob/bfa96ad2b3eb238d4f42bf33fddf19038b1aaa65/src/main/java/com/vaadin/flow/component/grid/Grid.java#L116) and set it to `0` in `setPageSize` method (https://github.com/vaadin/vaadin-grid-flow/blob/bfa96ad2b3eb238d4f42bf33fddf19038b1aaa65/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1063)

because of this, whenever the next property change occurred, correct `size` value on the client was overridden by 0 from the server.

The same issue caused https://github.com/vaadin/vaadin-grid-flow/issues/83 so, after fix for this issue is merged, the https://github.com/vaadin/vaadin-grid-flow/pull/102 PR can be reverted, if necessary.

**Closed** 2018-03-02 18:10 UTC
Labels: bug, components
