### ISSUE TITLE
Header row functionality is quite broken in many various ways

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-grid-flow#170] opened 2018-04-26 11:02 UTC
See the code below which shows that header row feature is broken.
You may use `com.vaadin.flow.component.grid.demo.GridView` class from the Grid demo
to see how it works ( just copy/paste).

See the result below in attached image.

Several things:
- the second added row in on the bottom but the third row is in the middle.
- the third added row has no any text though it has been set (if the second row is removed then it's shown fine).
- The second header row and the third row has sorting controls. Only one should have them.
- At the same time the first row doesn't have sorting controls (which means that rendering is done somehow differently).

Those issues are consequences of weird rendering implementation.
There is a method `renderHeader` in `Column`.
Which header it renders ?
If there are many header rows then logically this method has no sense.
Methods `setText` / `setComponent` in the `HeaderCell` are delegated to `
`getColumn()::setHeaderText` and `getColumn().setHeaderComponent`.
Which is illogical since column may have several header cells but all of them are handled via the same
column method which doesn't accept any parameter which identifies the cell/header.
Those methods do header rendering via `renderHeader` which the same `headerTemplate` instance of `Column` and adds `vaadin-grid-sorter`.

On the other hand I have no idea why it didn't add `vaadin-grid-sorter` for the first header row.

So the implementation is logically wrong.
There are a lot of issue which may be seen in the usecase.

```java
private void createGridWithDefaultHeader() {
        // begin-source-example
        // source-example-heading: xxxx
        Grid<Person> grid = new Grid<>();
        grid.setItems(createItems());

        Column<Person> nameColumn = grid.addColumn(Person::getName, "name")
                .setHeader("Name").setSortable(true);
        Column<Person> ageColumn = grid.addColumn(Person::getAge, "age")
                .setHeader("Age").setSortable(true);

        HeaderRow secondRow = grid.appendHeaderRow();

        secondRow.getCell(nameColumn).setComponent(new Text("a"));
        secondRow.getCell(ageColumn).setComponent(new Text("b"));

        HeaderRow thirdRow = grid.appendHeaderRow();

        thirdRow.getCell(nameColumn).setComponent(new Text("c"));
        thirdRow.getCell(ageColumn).setComponent(new Text("d"));

        // end-source-example
        addCard("Default header", "", grid);
    }
```

![Screen Shot 2018-04-26 at 1.49.24 PM.png](https://images.zenhubusercontent.com/5807311995e42b6c5baab5a6/a57f1e1f-26c9-4c08-922d-2046488c7184)

**Comment by pekam** [comment] 2018-04-26 11:40
These issues seem to occur only when you use components.
If you use `setText("a")` instead of `setComponent(new Text("a"))` it works fine.

> There is a method renderHeader in Column.
Which header it renders ?
If there are many header rows then logically this method has no sense.
Methods setText / setComponent in the HeaderCell are delegated to getColumn()::setHeaderText and getColumn().setHeaderComponent.

`cell.getColumn()` returns a component, which is either `<vaadin-grid-column>` or `<vaadin-grid-column-group>` and the rendering means setting this particular component's `<template class="header">`. So it is unambiguous where the header-rendering takes place. Yes, it is a bit confusing that `Column` is used internally as a Component but the public API considers it also as a more abstract column concept.

So the problem seems to be in how the `Column` overrides the component rendering to handle the sorter. I didn't think that too much because I was going to leave handling it to the `defaultHeaderRow` ticket. And I think I used `setText()` in all of my tests so I didn't realize that the component rendering was broken. Sorry for that mistake.

**Comment by denis-anisimov** [comment] 2018-04-26 12:35
It's true that it works somehow when `setText` is used for the header instead of `setComponent`.
But implementation is so clever that I'm not able to see a difference between `setText()` and `setComponent` when the rendering is done within a several hours.
I'm too dumb for this code apparently so I would like to be rather far away from it.

**Comment by pekam** [comment] 2018-04-26 16:45
I created a more descriptive ticket about the bug: https://github.com/vaadin/vaadin-grid-flow/issues/172
Closing this one.

**Closed by pekam** 2018-04-26 16:45 UTC

**Comment by denis-anisimov** [comment] 2018-04-26 17:01
I'm not sure that #172 is really more descriptive and actually supersede this one.

As I said from the very beginning I see logical problems in the implementation.
One of the aspects of the implementation which shows such logical issue:
- `Column::setHeader` delegates `setText` to the `HeaderCell:setText`.
- This is the implementation of the `HeaderCell:setText` : `getColumn().setHeaderText(text);`.
- Now `HeaderCell` is M:1 to Column.

So I have a question: how is this possible ? If I have a number of `HederCell`  instances for the same column and I call for all of the `setText`  then each if them will delegate `getColumn().setHeaderText(text);` which means override the previously set value.
It might be that implementation somehow works and is able to handle somehow cumulatively `getColumn().setHeaderText(text);` instead of overriding. 
But it's wrong. Regardless of the implementation. The contract is confusing and should contain a context: a cell (or a row which gives a cell for the column).
So I still think there a logical mistakes in the current approach which assumes there is only one header for the cell. In this case it works as expected. But with multiple header cells for the column it may not work as before.
Even if description in #172 is about one more bug. This logical issue still makes sense.

**Comment by gilberto-torrezan** [comment] 2018-04-27 05:56
The problem is mainly caused by the late assignment of the `<template>` contents to a given cell by the `ComponentRenderer`. It uses this structure to set it:

```
container.getNode()
                .runWhenAttached(ui -> 
                    ui.getInternals().getStateTree().beforeClientResponse(...));
```

When a column/cell is set to use a `ComponentRenderer`, it registers a `runWhenAttached` callback to that given cell, and it is never canceled when the renderer changes place (which happens when you `append` new rows). That causes the renderer to render its content in the wrong place.

**Comment by pekam** [comment] 2018-04-27 08:27
@gilberto-torrezan refer to https://github.com/vaadin/vaadin-grid-flow/issues/172 for that problem. The discussion here currently considers whether the implementation can work at all because it appears to be logically wrong. But it only appears to be so because of two different concepts of "column": a column in a grid, and the column/column-group element.

**Comment by pekam** [comment] 2018-04-27 09:36
> column which is the result if AbstractCell::getColumn() is not a Column at all.

Well, it is an instance of `AbstractColumn` which may be either `<vaadin-grid-column>` or `<vaadin-grid-column-group>`. The grid code has so far used the term "column" to refer to these components extending `AbstractColumn`.

But the API users don't need to know about these components. If they call `column.setHeader()` they don't care that there are multiple nested `<vaadin-grid-column>` and `<vaadin-grid-column-group>` components. They just want the header to go to the header row they expect (maybe the default header row). That's why the `Column` API has to redirect the `setHeader()` call to the correct header cell, which directs it to the correct column component.

**Comment by denis-anisimov** [comment] 2018-04-27 09:59
There is such thing as code maintenance and evolution.
The current code is quite un-maintainable  and doesn't really allow to evolve.
There are only few people who are able to write a new functionality on the top of the existing code.
I'm definitely not between them.
The code currently totally breaks separation of concerns. I've made an issue about it #173.

There is no reason to proceed the discussion further. This is my opinion which is described in #173.
You have your own opinion. That's normal and fine.

I'm not able to work with the `Grid` code in its current state.
I'm totally OK if the state will be preserved if I never assigned to any task related to `Grid`.

**Comment by pekam** [comment] 2018-04-27 10:13
> You have your own opinion. That's normal and fine.

Just to make sure if it was left unclear: I totally agree with you on this. I just didn't realize how big of a problem this was before your feedback.

I just disagreed you claiming that the whole header API is totally broken, and tried to convince you why it works, by explaining the code that unfortunately had become very difficult to understand. But I do agree that it is difficult to understand.

Anyway, thanks for writing the ticket!

**Comment by denis-anisimov** [comment] 2018-04-27 10:43
OK, good that it's clarified.

It's bad that I refer to API not on as the top level API but also implementation design.
It's actually also API since it's used by the other developers who are implementing the code. 
They shouldn't know absolutely all the details of the implementation. 
They should be able to use and see only part of exposed contract to be able to maintain and write a new code.
And that's an issue with the current code: you should start from `addColumn` method to understand how it works at all. But this method is totally unrelated to the thing that you are working on.

So the implementation design (which can be thought as an internal API) is broken in that sense.
In reality `Column` (and `AbstractColumn`) are components. And this should not be a part of _public_ API. It's just an implementation detail. And in this sense the _public_ API is also broken.
