### ISSUE TITLE
editorComponents do not disappear in buffered mode using demo code

### ISSUE THREAD

**Issue by thomasvamos** [vaadin/vaadin-grid-flow#568] opened 2019-03-05 17:19 UTC
Using the [vaadin components demo code](https://vaadin.com/components/vaadin-grid/java-examples/grid-editor), the editor is opened correctly, but does not disappear if editor.save() is called. See attached example [grid-editor-example.zip](https://github.com/vaadin/vaadin-grid-flow/files/2931997/grid-editor-example.zip)

This happens in Chrome 72 and Firefox 65.0.1

There is also a [forum thread](https://vaadin.com/forum/thread/17165917/how-to-edit-in-vaadin-10-grid) discussing this issue.

Thanks for your support :)

**Comment by denis-anisimov** [comment] 2019-03-06 07:25
Confirmed.

This is not a bug in the `Grid` editor.
This is a bug which happens during transferring internal demo class to the official demo.

Internal demo uses random data generator and produces persons whose First name starts with `Person`.
And there  is an example validator which checks that new name also starts with `Person`:
`withValidator(name -> name.startsWith("Person"),"Name should start with Person")`.

In the official demo this assumption is not correct and as a result the validation fails (if you use any meaningful name). And this is the reason why the editor is not closes.

The official demo needs to be corrected (either remove the validator or make it working in some sensible way).

The problem is : with autogenerated data the validator has some sense. And it's quite unclear how to create a good _visible_ validator (which shows that it sometimes works) with the official demo.
The validator may just check that the value is not empty of course. May be this is the only meaningful validator here.

**Comment by thomasvamos** [comment] 2019-03-06 12:15
Unfortunately the validators are not related to this effect. Even with simple or no validors the editor components do not disappear.

**Comment by denis-anisimov** [comment] 2019-03-06 12:43
This statement need a proof.

I've checked at least Grid master branch and verified that editor is closed.

> Using the vaadin components demo code, the editor is opened correctly, but does not disappear if editor.save() is called.

If you go to https://vaadin.com/components/vaadin-grid/java-examples/grid-editor, open an editor . and save then you will see a message in the top of the Grid which says that the First name should start with `Person`.
If you type `Person 1`  and save then the editor will save it and will be closed.

You attached example also contains code: 

```
binder.forField(field)
        .withValidator(name -> name.startsWith("Person"),
            "Name should start with Person")
        .withStatusLabel(validationStatus).bind("firstNam
```

This is direct copy-paste from you project.

So please provide a project where I can see the behavior which you described here:
>Unfortunately the validators are not related to this effect. Even with simple or no validors the editor components do not disappear.

**Comment by thomasvamos** [comment] 2019-03-13 19:33
You were right, the validator was the problem, I did not visualize the validationstatus and therefore didn't see the failed validation.

**Comment by denis-anisimov** [comment] 2019-03-14 05:33
The issue is still valid as a bug in our demo.
It's not obvious that the name should start with `Person` with the date which is used in the demo.

So the validation logic should be changed.
Editor itself doesn't have this issue.

**Closed** 2019-03-29 07:54 UTC
Labels: bug, demo
