### ISSUE TITLE
refreshItem() is not working

### ISSUE THREAD

**Issue by bisam-rd** [vaadin/vaadin-grid-flow#347] opened 2018-09-24 15:58 UTC
Vaadin Version: 10.0.4
Vaadin-Grid-Flow Version: 1.1.1
If you call grid.getDataProvider().refreshItem(selectedItem); the grid will not reflect the changes visually.
I'm attaching a demo application that reproduces the problem:

1. Select a row
2. Click on the "add" button, a new line is added in the tree under "Copernic" node
3. Click on the "delete" button, no line is deleted

If you call grid.getDataProvider().refreshAll() , the grid will change.

```
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.Span;
import com.vaadin.flow.component.treegrid.TreeGrid;
import com.vaadin.flow.data.provider.hierarchy.TreeData;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.Theme;
import com.vaadin.flow.theme.lumo.Lumo;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

@Route("vaadin-tree")
@Theme(Lumo.class)
public class VaadinTreeView extends Div {

    public VaadinTreeView() {

        Person galileo = create(1, "Galileo Galilei", "1564");
        Person copernicusFather = create(2, "Copernicus father (2)", "1500");
        Person copernicus = create(3, "Nicolaus Copernicus", "1543", copernicusFather);

        Set<Person> everyone = new HashSet<>(Arrays.asList(galileo,
                                                           copernicusFather,
                                                           copernicus,
                                                           create(4, "Johannes Kepler", "1571")));

        TreeData<Person> treeData = new TreeData<>();
        treeData.addItems(everyone.stream().filter(person -> person.parent == null),
                          parent -> everyone.stream().filter(person -> Objects.equals(person.parent, parent)));

        TreeGrid<Person> treeGrid = new TreeGrid();
        treeGrid.addHierarchyColumn(person -> person.name)
                .setHeader("Name");
        treeGrid.addColumn(person -> person.yearOfBirth)
                .setHeader("YoB");
        treeGrid.setTreeData(treeData);

        Span info = new Span();
        add(treeGrid);

        add(new Button("add", event -> {
                int id = (int)System.currentTimeMillis();
                Person tommy = create(id, "tom tommy " + id, "1985");
                treeData.addItem(galileo, tommy);
                treeGrid.getDataProvider().refreshAll();
                info.setText("[ADD] try to select " + tommy);
                treeGrid.getSelectionModel().select(tommy);
                treeGrid.expand(galileo);
            }),
            new Button("remove", event -> {
                treeGrid.getSelectionModel()
                        .getFirstSelectedItem()
                        .ifPresent(item -> {
                            treeData.removeItem(item);
                            treeGrid.getDataProvider().refreshItem(galileo); // Doesn't work
//                            treeGrid.getDataProvider().refreshAll(); //work
                        });

                info.setText("[REMOVE] try to select Copernicus Father <" + copernicusFather + "> (" +
                             "part of hierarchy " + treeGrid.getTreeData().contains(copernicusFather) + ")");
                treeGrid.getSelectionModel().select(copernicusFather);
            }),
            info);
    }

    @SuppressWarnings("SameParameterValue")
    private Person create(int id, String name, String yearOfBirth, Person parent) {
        return new Person(id, name, yearOfBirth, parent);
    }

    private Person create(int id, String name, String yearOfBirth) {
        return new Person(id, name, yearOfBirth, null);
    }

    private static class Person {
        final int id;
        final Person parent;
        final String name, yearOfBirth;

        Person(int id, String name, String yearOfBirth, Person parent) {
            this.id = id;
            this.parent = parent;
            this.name = name;
            this.yearOfBirth = yearOfBirth;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            Person person = (Person)o;
            return id == person.id &&
                   Objects.equals(parent, person.parent) &&
                   Objects.equals(name, person.name) &&
                   Objects.equals(yearOfBirth, person.yearOfBirth);
        }

        @Override
        public int hashCode() {
            return Objects.hash(id, parent, name, yearOfBirth);
        }
    }
}
```

**Comment by denis-anisimov** [comment] 2018-10-04 12:47
If I correctly understand your code the issue is :
- you have a `TreeGrid` and hierarchical data
- you remove some node and refresh its parent
- you are calling the `refreshItem` method on the parent 
- you expect that hierarchical structure of the parent will be refreshed.

If it true ?

I don't know why do you expect this. Is it documented somewhere?
This is never supposed to work in this way.
`refreshItem` only refresh the item data in a grid row. It never affects any other item (children or unrelated item).
`refreshAll` should be used to update items if structure is changed (new/removed items).

So if I understood you right this is at least not a bug.

It may be considered as a feature request but I'm not sure we are able to implement this since `refreshItem` is intended to update only item data not structural changes.

**Comment by denis-anisimov** [comment] 2018-10-22 07:33
I think my understand of the ticket is right.
At least there is no any comments from the reporter.
I'm closing the ticket since it's never supposed to work in the described way .

**Comment by denis-anisimov** [comment] 2018-10-22 07:33
I think my understand of the ticket is right.
At least there is no any comments from the reporter.
I'm closing the ticket since it's never supposed to work in the described way .

**Comment by denis-anisimov** [comment] 2018-10-22 07:34
I think my understand of the ticket is right.
At least there is no any comments from the reporter.
I'm closing the ticket since it's never supposed to work in the described way .

**Closed by denis-anisimov** 2018-10-22 07:33 UTC
Labels: bug, components
