### ISSUE TITLE
Details are no longer opened once parent in Treegrid is closed/reopened

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-grid-flow#751] opened 2019-08-26 10:23 UTC

**Comment by enver-haase** [comment] 2019-08-26 10:34
Please check out
https://github.com/enver-haase/Playground/tree/master/summarizing-tree
, commit aab4f668862af6fb34e6fade1ef4514251b12a8e .

Here the details of one line should always be shown when the (single-select) TreeGrid is clicked in that line, and the old one (if any) is closed.

Play with line "2.2.1" and see how it should work.
Close line "2.2".
Open line "2.2".
Play with line "2.2.1" and see it no longer works. Please fix with priority, a customer needs this.

**Comment by tomivirkki** [comment] 2019-08-26 11:06
Dupe of #732?

**Comment by jcgueriaud1** [comment] 2019-09-02 06:57
Closed by #732

**Closed by jcgueriaud1** 2019-09-02 06:57 UTC
Labels: BFP
