### ISSUE TITLE
gridConnector.js (cannot read property 'map' of null)

### ISSUE THREAD

**Issue by jflamy** [vaadin/vaadin-grid-flow#516] opened 2019-02-11 00:21 UTC
When using two very useful extensions together (crudui and app-layout) a Grid bug becomes visible -- a message (cannot read property 'map' of null) is reported.
See [bug report and minimal reproducible setup](https://github.com/alejandro-du/crudui/issues/45).

After investigation "appreciated", the author of app-layout, has identified a fix, see the [following screenshot](https://user-images.githubusercontent.com/1729845/52534538-129f4f80-2d43-11e9-833a-0fba3ce61840.PNG) for his suggested modifications.

**Comment by heruan** [comment] 2019-02-12 14:23
This is happening to me and I'm *not* using `Crud` nor `AppLayout`, just plain `Grid` with a data-provider and component columns.

**Comment by jflamy** [comment] 2019-02-12 14:32
The bug is in Grid.  Issue has been located and reported https://github.com/vaadin/vaadin-grid-flow/issues/516 and https://github.com/vaadin/vaadin-grid-flow/issues/515

**Comment by heruan** [comment] 2019-02-12 16:14
So this is basically a duplicate of #515? Better close it, then 🙂

**Closed** 2019-02-26 09:54 UTC
