### ISSUE TITLE
Empty list results in eternal loop

### ISSUE THREAD

**Issue by brp-oskar** [vaadin/vaadin-grid-flow#39] opened 2017-12-06 16:45 UTC
If a modify the demo code in function `createBasicUsage()` from `grid.setItems(getItems());` to `grid.setItems(new ArrayList<>());` it will result in an eternal request loop. It only happens when the list is empty.

The following request body is sent over and over again and the browser gets slow (testing on Chrome):
```
for(;;);[{"syncId":1332,"clientId":1332,"execute":[[[0,42],0,"$0.$connector.updateSize($1)"],[[0,42],0,0,"$0.$connector.clear($1,$2)"],[[0,42],0,[1,[]],"$0.$connector.set($1,$2)"],[[0,42],1332,"$0.$connector.confirm($1)"]],"timings":[422,0]}]
```

**Comment by pleku** [comment] 2017-12-07 06:54
Hello. Thanks for the feedback, I think this is a duplicate of #4 but let's check this anyway after that is fixed.

**Comment by brp-oskar** [comment] 2017-12-07 07:34
Yes, it's the same bug, i didn't see that one. You can remove this if you want to.

**Closed** 2017-12-07 07:37 UTC
Labels: bug, components
