### ISSUE TITLE
Flow : 14.0.0.alpha1  Grid rendered without styles 

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-grid-flow#626] opened 2019-04-18 08:28 UTC
**Vaadin Grid Flow: 3.0.3**
**Flow : 14.0.0.alpha1** 
Navigating to the view containing Grid rendereds it without proper styles being applied. Try to scroll--> The header is on top of content.  There are no rows/columns delimiter lines. 
Example to reproduce in attachments.
**Expected**: 
![expected](https://user-images.githubusercontent.com/15248706/56347361-cf42e080-61cc-11e9-88be-d3cbfb276718.JPG)

**Actual:**
![actual](https://user-images.githubusercontent.com/15248706/56347377-d538c180-61cc-11e9-8fc9-eb00b1a60ebe.JPG)
[gridloading.zip](https://github.com/vaadin/vaadin-grid-flow/files/3093416/gridloading.zip)

 The code from the example:

GridView: 
```

import com.vaadin.flow.component.grid.ColumnTextAlign;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.data.renderer.ComponentRenderer;
import com.vaadin.flow.data.renderer.LocalDateRenderer;
import com.vaadin.flow.router.Route;

import java.time.LocalDate;
import java.util.stream.IntStream;

@Route( value= "grid-view",layout = MainView.class)
public class GridView extends VerticalLayout {

        public GridView(){
                Grid<String> grid = new Grid<String>();
                grid.addColumn(string->String.valueOf(Math.random())).setHeader("column 1");
                grid.addColumn(string->String.valueOf(Math.random())).setHeader("column 2");
                grid.addColumn(string->"Loooooooooooooooooooooooong test").setHeader("column 3").setWidth("45px").setClassNameGenerator(item->"truncateLeft");
                grid.addColumn(value -> LocalDate.now()).setHeader("date");
                grid.addColumn(new LocalDateRenderer<>(item -> LocalDate.now()))
                        .setHeader("LocalDateRender")
                        .setResizable(true)
                        .setSortable(true);

                grid.addColumn(new ComponentRenderer<>(att -> {
                        if (att.equals("1")) {
                                Icon yep = new Icon(VaadinIcon.CHECK);
                                yep.setColor("lime");
                                return yep;
                        } else {
                                Icon nope = new Icon(VaadinIcon.CLOSE);
                                nope.setColor("red");
                                return nope;
                        }
                })).setHeader("Verified").setTextAlign(ColumnTextAlign.CENTER).setKey("districtVerified").setSortable(true);
                grid.addComponentColumn(item-> new TextField());
                grid.setPageSize(20);
                grid.setItems(IntStream.rangeClosed(1, 120000).mapToObj(number -> String.valueOf(number)));
                 add(grid);
        }
}
```
MainView from where we are navigating: 
```

import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.html.Span;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.page.BodySize;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouterLayout;
import com.vaadin.flow.router.RouterLink;
import com.vaadin.flow.server.PWA;

/**
 * The main view contains a button and a click listener.
 */
@Route("")

@BodySize(height = "100%", width = "100%")
@PWA(name = "Project Base for Vaadin Flow", shortName = "Project Base")
public class MainView extends VerticalLayout implements RouterLayout {

    public MainView() {
        VerticalLayout menu=new VerticalLayout();
        menu.add(addRoute(VaadinIcon.TABLE,"Grid", GridView.class));
        menu.setWidth("20%");
        Button navigate=new Button("Navigate to Grid View", e->{
            UI.getCurrent().navigate("grid-view");
        });
        menu.add(navigate);
        add(menu);
    }
    private RouterLink addRoute(VaadinIcon icon, String caption, Class cls){
        RouterLink rl=new RouterLink(null,cls);
        rl.add(new Icon(icon));
        rl.add(new Span(caption));
        return rl;
    }
}
```
Broken both using `RouterLink` and `UI.getCurrent().navigateTo`

Worked fine in 13.0.3

**Comment by ericmartinezr** [comment] 2019-05-15 14:39
Same happened to me when trying 14.0.0.beta1. I fixed it by cleaning the cache, or using the dev console and disabling cache when reloading.

**Comment by heruan** [comment] 2019-05-15 15:23
Duplicate of https://github.com/vaadin/flow/issues/5642

Cleaning the cache isn't a fix, it happens regardless of the cache when navigating in-app.

**Comment by caalador** [comment] 2019-06-13 08:42
Tested and found working as expected with beta2.
Closing as fixed. Please reopen ticket with new data if for some reason the issue persists.

**Closed by caalador** 2019-06-13 08:42 UTC
