### ISSUE TITLE
Problem displaying icons inside Grid in Chrome 72

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-grid-flow#534] opened 2019-02-15 20:09 UTC
Vaadin version: 12.0.6

Chrome version: 72.0.3626.109 (Build oficial) (64 bits)

Adding icons inside a cell of a grid, shows them in Firefox and in Edge (wasn't able to test it in IE11), but not in Chrome. If I open Chrome Developers Tools, and then Toggle Device Toolbar, then icon appears, but then, if I disable it, and refresh, they disappear again.

This is the code to reproduce the issue:

```
		Grid<String> grid = new Grid<>();
		grid.addColumn(new ComponentRenderer<>(att -> {
			if (att.equals("1")) {
				Icon yep = new Icon(VaadinIcon.CHECK);
				yep.setColor("lime");
				return yep;
			} else {
				Icon nope = new Icon(VaadinIcon.CLOSE);
				nope.setColor("red");
				return nope;
			}
		})).setHeader("Verified");
		
		grid.setItems("1","0");
		add(grid);
```
This is a short animated gif showing the described behavior:
![gridiconsproblem](https://user-images.githubusercontent.com/28312758/52881797-67c4d200-3144-11e9-8774-fa0f7d9b9b31.gif)

**Comment by TatuLund** [comment] 2019-02-16 08:29
I think this is duplicate of

https://github.com/vaadin/vaadin-grid/issues/1563

and

https://github.com/vaadin/vaadin-grid/issues/1563

Which are luckily fixed in next release of Vaadin 12 & 13.

**Comment by web-padawan** [comment] 2019-02-16 10:46
Yes, that's also duplicate of [vaadin/flow#5025](https://github.com/vaadin/flow/issues/5025) which is already fixed in Flow.
We understand the importance of this issue so the team will take care of delivering the fix ASAP.

**Closed by web-padawan** 2019-02-16 10:46 UTC
Labels: duplicate
