### ISSUE TITLE
Uncaught TypeError: Cannot read property 'doSelection' of undefined

### ISSUE THREAD

**Issue by oltzen** [vaadin/vaadin-grid-flow#706] opened 2019-07-07 10:05 UTC
Here is the source code of an example. If I update a deattached grid, and the grid will be attached again, I get an java script exception. 

If I call the update Grid on the 2. position, I must press the back botton twice.  

import java.util.ArrayList;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.data.selection.SelectionEvent;

public class Example extends VerticalLayout {

	Grid<String> grid = new Grid<>();
	
	Button back = new Button("back");
	
	public Example() {
		grid.addColumn(e -> e).setHeader("bla");
		grid.addSelectionListener( e -> select(e));
		updateGrid();
		add(grid);
		back.addClickListener(e -> doBack());
	}

	private void doBack() {
		this.remove(back);
		updateGrid();
		this.add(grid);
		// updateGrid(); 2. Position
	}

	private void updateGrid() {
		ArrayList<String> list = new ArrayList<>();
		list.add("basdlkf");
		list.add("laksdfh");
		grid.setItems(list);
	}

	private void select(SelectionEvent<Grid<String>, String> e) {
		this.remove(grid);
		this.add(back);
	}
	
	
}

**Comment by pekam** [comment] 2020-01-30 11:30
This issue seems to be a duplicate of #763, so I'll close this one.

Anyway, thanks for the code snippet!

**Closed by pekam** 2020-01-30 11:30 UTC
