### ISSUE TITLE
Javascript error when filtering grid with a large dataset

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-grid-flow#1053] opened 2020-06-25 12:08 UTC
## Vaadin version
14.2.1
## vaadin-grid-flow version
4.1.4
## Description of the problem
When scrolling to the middle of a grid with a large dataset and then filtering so it matches one of the first rows, then a javascript error appears. 
![GridError](https://user-images.githubusercontent.com/28312758/85716426-cf891680-b6c2-11ea-81fd-ad5b18b21819.gif)

## Expected behavior
The error should not appear and the filtered row should be shown instead

## Code to reproduce the issue:
```
@Route
public class MainView extends VerticalLayout {

    public MainView() {
    	Grid<String> grid = new Grid<>();
    	ListDataProvider<String> ldp = new ListDataProvider<>(
    			IntStream.range(0, 200000)
    			.mapToObj(number->"Item: ".concat(String.valueOf(Math.random()*100000)))
    					.collect(Collectors.toList()));
    	grid.setDataProvider(ldp);
    	grid.addColumn(i->i).setHeader("Item");
    	
    	TextField tf = new TextField();
    	tf.addValueChangeListener(ev->{
    		ldp.setFilter(item->passesFilter(item,ev.getValue()));
    	});
    	add(tf,grid);
    }
    
    private boolean passesFilter(Object object, String filterText) {
        return object != null && object.toString().toLowerCase(Locale.ENGLISH)
                .contains(filterText);
    }
}
```

**Comment by jcgueriaud1** [comment] 2020-07-06 13:48
If you set the list size to 100000 then you don't have the bug. From 100001, you can reproduce the error.

**Comment by jcgueriaud1** [comment] 2020-07-07 13:20
The problem is related to the virtual items set to 100.000 in vaadin-grid-scroller
`const maxVirtualItems = this._edge || this._ie ? 30000 : 100000;`

If you changed the default value to 300000 then it's _working_. This 'magic' number causes also this error: https://github.com/vaadin/vaadin-grid/issues/1659 

I don't know if it's related.

**Comment by jcgueriaud1** [comment] 2020-07-17 10:36
The component has a bug that cause the javascript error in the vaadin-grid-flow.

Here is the same example in Javascript. There is no javascript error but the data displayed in the grid is wrong (from the cache).

```
import {html, PolymerElement} from "@polymer/polymer/polymer-element.js";
import '@vaadin/vaadin-grid/vaadin-grid.js';
import '@vaadin/vaadin-grid/vaadin-grid-column-group.js';
import '@vaadin/vaadin-grid/vaadin-grid-filter-column.js';

export class VaadinGridTest extends PolymerElement {
static get template() {
    return html`<vaadin-grid id="grid" aria-label="Filtering Example">
    <vaadin-grid-filter-column path="value"></vaadin-grid-filter-column>
  </vaadin-grid>
        <button id="scrollbottom">Scroll bottom</button>
`;
}

ready() {
  super.ready();
  const grid = this.$.grid;
  const maxGridSize = 300000;
  grid.dataProvider = (params, callback) => {
    let numberOfElements = maxGridSize;
    params.filters.forEach(function (filter) {
      if (isNaN(filter.value)) {
        numberOfElements = maxGridSize;
      } else {
        numberOfElements = filter.value;
      }
    });
    grid.size = numberOfElements;
    var response = [];
    for (var i=0;i<=params.pageSize;i++) {
      var element = params.page * params.pageSize + i;
      if (element < grid.size) {
        response.push({value: element});
      }
    }
    callback(response);
  };
  const button = document.getElementById("scroll-top");
  const scrollBottom = this.$.scrollbottom;
  scrollBottom.addEventListener("click", function(){
    grid.scrollToIndex(grid.size);
  });
  }
}
```

This issue is only there if the grid size is > 100000.

**Comment by tomivirkki** [comment] 2020-08-07 12:34
Fixed by https://github.com/vaadin/vaadin-grid/pull/1777 -> https://github.com/vaadin/vaadin-grid/pull/1778

**Closed by tomivirkki** 2020-08-07 12:34 UTC
Labels: BFP, Impact: Low, Severity: Major
