### ISSUE TITLE
Can’t click a button inside a column using Space

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid-flow#122] opened 2018-03-15 10:15 UTC
A `<vaadin-button>` inside a column can’t be clicked with the keyboard <kbd>Space</kbd> when the cell is focused.

This is reproducible in BeverageBuddy “Categories” view.

<img width="1054" alt="screen shot 2018-03-15 at 12 15 48" src="https://user-images.githubusercontent.com/66382/37457430-a6f96b24-284a-11e8-956b-d46c1a6a937d.png">

I’m expecting that `<flow-grid-component-renderer>` causes this – `<vaadin-grid>` doesn’t consider nested buttons/focusable elements when triggering the click. Therefore it might be that this needs a fix in the web component and not in the Flow wrapper.

See https://vaadin.com/components/vaadin-grid/html-examples#grid-selection-demos (last example) for reference how it should work.

@platosha can probably answer right away?

**Comment by pleku** [comment] 2018-03-15 13:34
>I’m expecting that <flow-grid-component-renderer> causes this – <vaadin-grid> doesn’t consider nested buttons/focusable elements when triggering the click.

This might be the root cause for https://github.com/vaadin/vaadin-grid-flow/issues/74 also.

**Comment by platosha** [comment] 2018-03-19 08:13
> I’m expecting that <flow-grid-component-renderer> causes this – <vaadin-grid> doesn’t consider nested buttons/focusable elements when triggering the click.

True: https://github.com/vaadin/vaadin-grid/blob/9f466f3547f86298b029c0a6eea6947ea5bbe52c/src/vaadin-grid-keyboard-navigation-mixin.html#L419

**Comment by bennewi** [comment] 2018-05-29 08:07
Similar to if you use a keyboard to navigate to a cell in a Grid that contains a TextField, you can't enter data in the TextField

**Comment by tomivirkki** [comment] 2018-05-29 08:57
`<vaadin-grid>` invokes `click()` on the first child element inside the focused cell on space press as a convenience.

To fix this issue (caused by wrapping of the content), listen to `click` events on `<flow-grid-component-renderer>` element and in the listener, invoke `click()` on its first child element respectively.

**Comment by bennewi** [comment] 2018-05-29 09:35
Is it not better, if the cell gets focus, that an evaluation is made if the cell has a component renderer and if so, immediately pass the focus to the embedded component? This way you wouldn't be treating "space" and "click" as separate cases but you could interact with any component as though it were the cell

**Comment by tomivirkki** [comment] 2018-05-29 10:11
@bennewi I think we're talking about a different things here. This ticket is about the "space press click" feature. Focusing an element inside a cell is a different thing and done with Enter key (by entering the interaction mode).

**Comment by jouni** [comment] 2018-05-29 10:40
> an evaluation is made if the cell has a component renderer and if so, immediately pass the focus to the embedded component

The web component doesn’t have a concept of a “component renderer”. AFAIK that’s a Flow concept. I don’t think we should add workarounds in the web component on top of Flow’s workarounds.

**Comment by tomivirkki** [comment] 2018-05-29 11:18
@bennewi In case the focusable element is wrapped (like I assume in this case), you can add `focus-target` attribute to the element to get it focused on enter.

**Comment by bennewi** [comment] 2018-05-29 11:49
@tomivirkki Should `focus-target` not be the default behavior always? What is the usefulness of pressing enter and losing all focus with the Grid, Cell, and Cell contents all at once?

**Comment by tomivirkki** [comment] 2018-05-29 13:10
@bennewi It's focusing the first child element by default (if a `focus-target` isn't defined). Again, this discussion should happen somewhere else because it's about another topic.

**Comment by jouni** [comment] 2018-06-07 10:40
This reproducible, in Chrome, Safari and Firefox on macOS.

Are you sure you tested the Categories list, and not the Reviews list? The reviews list is not using vaadin-grid.

In the Categories list, use the Tab key to move the focus to the grid body. Then use the arrow keys to move the focus to the cell which contains the Edit button. Then press Space. Nothing happens.

The test you added doesn’t really test this behavior, as you are sending the Space key event directly to the button element, not for the cell element.

**Comment by denis-anisimov** [comment] 2018-06-07 11:01
True, I've used reviews list.
Yes, I can reproduce it now with categories list.
Not sure that its possible to write the test for this at all. But at least will try to fix the issue.

**Comment by jouni** [comment] 2018-06-08 12:48
Was the issue actually fixed, or did you just add the test for it?

**Comment by ZheSun88** [comment] 2018-06-08 12:49
the fix is from flow side, PR https://github.com/vaadin/flow/pull/4244  has been merged

**Comment by ZheSun88** [comment] 2018-06-12 08:38
The current fix has been reverted, because of the side effects on overlay component

**Comment by denis-anisimov** [comment] 2018-06-12 08:40
The test is disabled : https://github.com/vaadin/vaadin-grid-flow/pull/226
Should be enabled back once the fix is provided.
The original fix is reverted : https://github.com/vaadin/flow/pull/4269.
The fix cannot be done in this way.

**Closed** 2018-06-27 04:51 UTC
Labels: UX, bug, components
