### ISSUE TITLE
Grid components are not always rendered - regression in Chrome 73

### ISSUE THREAD

**Issue by Klaudeta** [vaadin/vaadin-grid-flow#600] opened 2019-03-22 10:18 UTC
This was an issue introduced in Chrome 72 [vaadin-grid-flow/issues/557](https://github.com/vaadin/vaadin-grid-flow/issues/557).
It was fix by  [PR #5223](https://github.com/vaadin/flow/pull/5223). Bit now it has regressed in Chrome 73

Vaadin version affected: Vaadin 10.0.11

**Comment by gianluca-valentini** [comment] 2019-03-25 11:32
Hi,
I have the same problem using Vaadin 13.0.1. Any news about it?

**Comment by drewharvey** [comment] 2019-04-30 21:59
This is still an issue in Chrome 74 and Vaadin 13.0.4.  Here is an example of how to repro 100%:

`Grid<String> grid = new Grid<>();
grid.addComponentColumn(str -> {
	Div div = new Div();
	div.setText(str);
	div.setTitle(str);
	return div;
});
grid.setWidth("100%");
grid.setSelectionMode(Grid.SelectionMode.NONE);
grid.setItems(
		Arrays.asList(
				"sdfa sfas dfdfasdffasdffasfdsfsa afsdfs adfasf asdf asdfa sdf asdf ",
				"sdfjkfdj fjadskjfa;fd k;alskdjf jasdfjdsfjasdfjsfjsaklfjs;f d;sfjaksfj;jdaslf;jaf;jadskl;fjsa fsadfjksaf",
				"fasjdfa kfsdf",
				"asd fasjfksad;flsafsadj f;sfklsajfkdsf;safja;djas;lf ja;fja;",
				"sdfjkfdj fjadskjfa;fd k;alskdjf jasdfjdsfjasdfjsfjsaklfjs;f d;sfjaksfj;jdaslf;jaf;jadskl;fjsa fsadfjksaf",
				"sdfjkfdj fjadskjfa;fd k;alskdjf jasdfjdsfjasdfjsfjsaklfjs;f d;sfjaksfj;jdaslf;jaf;jadskl;fjsa fsadfjksaf",
				"sdfjkfdj fjadskjfa;fd k;alskdjf jasdfjdsfjasdfjsfjsaklfjs;f d;sfjaksfj;jdaslf;jaf;jadskl;fjsa fsadfjksaf",
				"sdfjkfdj fjadskjfa;fd k;alskdjf jasdfjdsfjasdfjsfjsaklfjs;f d;sfjaksfj;jdaslf;jaf;jadskl;fjsa fsadfjksaf",
				"sdfjkfdj fjadskjfa;fd k;alskdjf jasdfjdsfjasdfjsfjsaklfjs;f d;sfjaksfj;jdaslf;jaf;jadskl;fjsa fsadfjksaf",
				"sdfjkfdj fjadskjfa;fd k;alskdjf jasdfjdsfjasdfjsfjsaklfjs;f d;sfjaksfj;jdaslf;jaf;jadskl;fjsa fsadfjksaf",
				"asdfjsa;fdfjkfasjkf;js"));

Div div = new Div();
div.add(grid);
div.getStyle().set("overflow-x", "scroll");
div.setWidth("300px");
div.setHeight("100px");
div.getStyle().set("flex-grow", "0");

add(div);`

**Comment by tomivirkki** [comment] 2019-05-07 11:37
The items in the seemingly random list of Strings aren't unique and it looks like the duplicates are causing the issue. Doesn't relate to the original issue caused by a known Chrome rendering bug which was fixed in Chrome 74.

**Comment by drewharvey** [comment] 2019-05-07 18:09
@tomivirkki Should I open a new issue for this then?  I didn't think to check if it were caused by duplicate values.

**Comment by tomivirkki** [comment] 2019-05-08 09:16
My gut feeling is that duplicate items aren't even supposed to work. Selection etc are after all based on unique items. @pleku?

**Comment by pleku** [comment] 2019-05-08 09:51
If two items are considered equal (in Java) by the data provider, that does bring lots of issues and thus is implicitly not supported. It probably should be made explicit somewhere (if not already).

I don't think this issue (in the description) is anymore valid since the workaround for chrome we have checks the major version of chrome and applies the workaround for anything >71.

**Comment by drewharvey** [comment] 2019-05-15 17:02
Ok thank you guys.  I just had to the wrap the strings coming from the database in a simple object and the rows all displayed correctly!  In our case we were parsing a list of system messages from a large, single string (coming from the db) so having duplicates was common.  Should this be noted somewhere in the docs?

**Closed** 2019-05-27 12:16 UTC
Labels: bug, components
