### ISSUE TITLE
Grid components not rendered - an example

### ISSUE THREAD

**Issue by andreasbean** [vaadin/vaadin-grid-flow#606] opened 2019-03-26 12:46 UTC
```
Grid<Integer> grid = new Grid();

grid.addColumn((value) -> { return value;}).setHeader("Value").setWidth("50px").setFlexGrow(0); 

grid.addColumn(new ComponentRenderer<>(value -> {
    Div vl = new Div();
    if (value == 5) {
        DatePicker datepicker = new DatePicker();
        datepicker.setLocale(Locale.GERMANY);
        LocalDate date = LocalDate.of(2019, 1, 1);
        datepicker.setValue(date);
        vl.add(datepicker);
    }
    return vl;
})).setWidth("150px").setFlexGrow(1).setHeader("Date"); 

ArrayList<Integer> numbers = new ArrayList();
for (int i = 1; i < 100; i++) {
    numbers.add(i);
}

ListDataProvider<Integer> dataProvider = DataProvider.ofCollection(numbers);

grid.setDataProvider(dataProvider);
```

Interestingly, when the line `datepicker.setValue(date);` is removed, then the component is rendered.  Also, when not rendered in first place, after a bit of scrolling the component gets shown. What's going on here?

Versions are Vaadin 13.0.2 and Chrome 72.0.3626.121

**Comment by web-padawan** [comment] 2020-02-20 18:49
Seems to be the same as #5025 - Chrome 72 regression (see https://github.com/vaadin/flow/issues/5025#issuecomment-462668991)
Workarounded by vaadin/flow#5060. Also, the issue is fixed in more recent Chrome versions.

**Closed by web-padawan** 2020-02-20 18:49 UTC
