### ISSUE TITLE
TreeGrid expand many

### ISSUE THREAD

**Issue by clivemoj** [vaadin/vaadin-grid-flow#864] opened 2020-01-14 11:17 UTC
Vaadin Flow Version: 14.1.5

Expanding several tree nodes on a large tree using #expandRecursive(level) causes massive client side lag.
It seems like the client side update nodes in random order using a lot of slow server round-trips.
The client also seems to update and expands nodes that would be outside viewable scope should it have expanded nodes top down.
This behavior is also true on initial rendering, when it actually should know about all visible nodes based on their expanded state.
Do some scrolling during this process and things gets really weird.

This problem will prevent us from putting a Vaadin 14 based version into production, we will be forced to stay on Vaadin 8.

/Joakim @ Ortelius

**Comment by mehdi-vaadin** [comment] 2020-01-15 16:23
Thank you @clivemoj for reporting this. I moved it to the correct repository. It may be a duplicate of #476.

**Comment by web-padawan** [comment] 2020-01-21 12:14
Closing as a duplicate of #476 per above comment. We will investigate the performance of `expandRecursive`

**Closed by web-padawan** 2020-01-21 12:14 UTC

**Comment by tomivirkki** [comment] 2020-01-28 13:14
@clivemoj Can you provide a minimal reproduction for the issue (a view class with only the bare minimals for producing the issue)? At least the "TreeGrid Basics" demo at https://vaadin.com/components/vaadin-tree-grid/java-examples seems expand ok with "Toggle first item recursively" click (which uses expandRecursively internally).

**Comment by clivemoj** [comment] 2020-01-29 18:47
Yes of course. 
My colleague has put a nice little example together.

Note that this is NOT about expanding one root, rather all roots.
Server side expandRecursively is NOT the problem, it is the client side that almost kills the browser and leaves the user wondering "what's going on?".

[treegriddemo.zip](https://github.com/vaadin/vaadin-grid-flow/files/4130024/treegriddemo.zip)

**Comment by Ortofta** [comment] 2020-01-29 18:59
Hi - clivemojs colleague here. 

It might also be worth mentioning that if you scroll around a little while the tree is expanding, you will most likely encounter this error at some point:
![TreeGrid_Error](https://user-images.githubusercontent.com/4502994/73387892-867a9500-42d1-11ea-8c0a-20a9b4630c43.png)

**Comment by tomivirkki** [comment] 2020-01-30 07:30
Thanks for the repro. If this issue doesn't get fixed by the upcoming fix for https://github.com/vaadin/vaadin-grid-flow/issues/476, we'll re-open this one.

**Comment by Ortofta** [comment] 2020-02-27 10:04
I tested Vaadin Grid version 4.1.3 where issue #476 is fixed, with the example application submitted to this issue. While the expansion and loading of the initial items are much faster, we still encounter some strange behavior related to scrolling:

* The scroll wheel doesn't seem to work for scrolling the grid
* Scrolling during the expansion phase causes a lot of errors to be logged in the browser console:
`There seems to be an error in the Vaadin Grid:
too much recursion
Please submit an issue to https://github.com/vaadin/vaadin-grid-flow/issues/new! localhost:8080:2:1704
    tryCatchWrapper (index):2
    beforeEnsureSubCacheForScaledIndex gridConnector.js:149
    flushQueue gridConnector.js:270
    tryCatchWrapper (index):2
    flushQueue gridConnector.js:278......`
* An error was logged on the server, also when scrolling during node expansion:
`java.lang.IndexOutOfBoundsException: fromIndex = -300
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:505) ~[na:na]
	at java.base/java.util.ArrayList.subList(ArrayList.java:1104) ~[na:na]
	at com.vaadin.flow.data.provider.hierarchy.HierarchicalCommunicationController.collectKeysToFlush(HierarchicalCommunicationController.java:242) ~[flow-data-2.1.5.jar:2.1.5]
	at com.vaadin.flow.data.provider.hierarchy.HierarchicalCommunicationController.flush(HierarchicalCommunicationController.java:127) ~[flow-data-2.1.5.jar:2.1.5]
	at com.vaadin.flow.data.provider.hierarchy.HierarchicalDataCommunicator.lambda$requestFlush$e15592a2$1(HierarchicalDataCommunicator.java:137) ~[flow-data-2.1.5.jar:2.1.5]
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$1(StateTree.java:368) ~[flow-server-2.1.5.jar:2.1.5]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507) ~[na:na]
	at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:365) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:411) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:187) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:121) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:95) ~[vaadin-spring-12.1.2.jar:na]`
* On one occasion only the 5 first nodes were populated, after that nothing more happened (all nodes were rendered as expanded with the "down arrow", but no children were ever rendered).

I tested by using Vaadin BOM 4.1.17, and substituting the Grid dependencies in the pom file:
` <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <version>14.1.17</version>
                <type>pom</type>
                <scope>import</scope>
	            <exclusions>
		            <exclusion>
			            <groupId>com.vaadin</groupId>
			            <artifactId>vaadin-grid-flow</artifactId>
		            </exclusion>
	                <exclusion>
		                <groupId>com.vaadin</groupId>
		                <artifactId>vaadin-grid</artifactId>
	                </exclusion>
	            </exclusions>
            </dependency>
	        <dependency>
		        <groupId>com.vaadin</groupId>
		        <artifactId>vaadin-grid-flow</artifactId>
		        <version>4.1.3</version>
	        </dependency>
	        <dependency>
		        <groupId>com.vaadin</groupId>
		        <artifactId>vaadin-grid</artifactId>
		        <version>5.5.2</version>
	        </dependency>
        </dependencies>
    </dependencyManagement>`

This seems to give me the required Flow version (2.1.5), and the correct Grid component versions.
Is this a valid way to test the fix, or is there a better way?

All tests were performed in Firefox 73.0.1

**Comment by tulioag** [comment] 2020-02-28 11:49
@Ortofta I was unable to reproduce these:
> - The scroll wheel doesn't seem to work for scrolling the grid
> - On one occasion only the 5 first nodes were populated, after that nothing more happened (all nodes were rendered as expanded with the "down arrow", but no children were ever rendered).
I will create a new issue for the other 2 points.

**Comment by Ortofta** [comment] 2020-02-28 12:07
Thanks for checking, @tulioag.

For me, the scroll wheel doesn't work in Firefox, but it works in Edge Chromium (hence I assume it also works in Chrome). Might be local to my machine, though (Windows 10, Firefox 73.0.1).

The second issue I was only able to provoke by scrolling violently up and down in the grid while expanding all nodes. I did it again in Edge Chromium just now - quite a few errors are logged in the browser console:

![TreeGrid-Crash](https://user-images.githubusercontent.com/4502994/75547218-b92bc080-5a2a-11ea-862a-cc0991089588.png)

along with this in the server log:
`java.lang.IndexOutOfBoundsException: toIndex = 200
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507) ~[na:na]
	at java.base/java.util.AbstractList.subList(AbstractList.java:497) ~[na:na]
	at com.vaadin.flow.data.provider.hierarchy.HierarchicalCommunicationController.collectKeysToFlush(HierarchicalCommunicationController.java:242) ~[flow-data-2.1.5.jar:2.1.5]
	at com.vaadin.flow.data.provider.hierarchy.HierarchicalCommunicationController.flush(HierarchicalCommunicationController.java:127) ~[flow-data-2.1.5.jar:2.1.5]
	at com.vaadin.flow.data.provider.hierarchy.HierarchicalDataCommunicator.lambda$requestFlush$e15592a2$1(HierarchicalDataCommunicator.java:137) ~[flow-data-2.1.5.jar:2.1.5]
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$1(StateTree.java:368) ~[flow-server-2.1.5.jar:2.1.5]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507) ~[na:na]
	at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:365) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:411) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:187) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:121) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:95) ~[vaadin-spring-12.1.2.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.27.jar:9.0.27]`

Only way to recover from that is to reload the page, after which it works as expected again.

**Comment by tulioag** [comment] 2020-02-28 12:39
Scrolling with the scroll wheel works for me in Firefox 73.0.1 (64-bit) on Linux, but I do get a warning in the console:
![message](https://user-images.githubusercontent.com/28783969/75549271-edf24480-5a37-11ea-9fb2-c6f8bf3e7b32.png)

**Comment by Ortofta** [comment] 2020-02-28 13:27
@tulioag, I asked a colleague to test it - and for him the scroll wheel is working in FF 73.0.1 on Windows 10. I guess it's something on my machine that cause issues (maybe some extension or something is intervening).

So you're off the hook for that. :)

**Comment by tulioag** [comment] 2020-02-28 14:14
At least that. :)

I created https://github.com/vaadin/vaadin-grid-flow/issues/894. Thanks for reporting.
