### ISSUE TITLE
TreeGrid is not working in V10 but working well in V8 with the same code

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/vaadin-grid-flow#301] opened 2018-08-04 21:24 UTC
I use TreeGrid in V8 and it is working fine. But I can not use TreeGrid with Vaadin 10 -> Flow.
The code is nearly the same, but none of children nodes are listed in the Grid; V10 TreeGrid shows only the root nodes. Here is the codes I use (below):

**Version Information: 1.1.0.beta1**

```
public class ProductCategoryDto implements Serializable {

    private Integer                idProductCategory;
    private ProductCategoryDto    productCategory;
    private State                state;
    private Date                registerDate;
    private String                name;
    private int                    sequenceNumber;
    private String                pathLogo;

    private Set<ProductCategoryDto> productCategories = new HashSet<ProductCategoryDto>( 0 );

    public ProductCategoryDto( ) {}

    public Integer getIdProductCategory( ){

        return idProductCategory;
    }

    public void setIdProductCategory( Integer idProductCategory ){

        this.idProductCategory = idProductCategory;
    }

    public ProductCategoryDto getProductCategory( ){

        return productCategory;
    }

    public void setProductCategory( ProductCategoryDto productCategory ){

        this.productCategory = productCategory;
    }

    public State getState( ){

        return state;
    }

    public void setState( State state ){

        this.state = state;
    }

    public Date getRegisterDate( ){

        return registerDate;
    }

    public void setRegisterDate( Date registerDate ){

        this.registerDate = registerDate;
    }

    public String getName( ){

        return name;
    }

    public void setName( String name ){

        this.name = name;
    }

    public int getSequenceNumber( ){

        return sequenceNumber;
    }

    public void setSequenceNumber( int sequenceNumber ){

        this.sequenceNumber = sequenceNumber;
    }

    public String getPathLogo( ){

        return pathLogo;
    }

    public void setPathLogo( String pathLogo ){

        this.pathLogo = pathLogo;
    }

    public Set<ProductCategoryDto> getProductCategories( ){

        return productCategories;
    }

    public void setProductCategories( Set<ProductCategoryDto> productCategories ){

        this.productCategories = productCategories;
    }

    // manipulation methods
    @Override
    public String toString( ){

        return "ProductCategoryDto [idProductCategory=" + idProductCategory + ", productCategory=" + productCategory + ", state=" + state
                + ", registerDate=" + registerDate + ", name=" + name + ", sequenceNumber=" + sequenceNumber + ", pathLogo=" + pathLogo
                + ", productCategories=" + productCategories + "]";
    }

    public List<ProductCategoryDto> getProductCategoriesAsList( ){

        List<ProductCategoryDto> list = new ArrayList<>( );
        list.addAll( productCategories );
        return list;
    }
}

private List<ProductCategoryDto> getRoots( ){

        List<ProductCategoryDto> roots = new ArrayList<>( );

        for ( int year = 2017; year <= 2018; year++ ) {
            ProductCategoryDto root = new ProductCategoryDto( );
            root.setName( "YEAR_ " + year );

            for ( int i = 1; i < 3; i++ ) {
                ProductCategoryDto child = new ProductCategoryDto( );
                child.setName( "PROJECT_ " + i );

                Set<ProductCategoryDto> grandChildren = new HashSet<>( );

                ProductCategoryDto gc1 = new ProductCategoryDto( );
                gc1.setName( "Impl" );
                gc1.setSequenceNumber( year );
                grandChildren.add( gc1 );

                ProductCategoryDto gc2 = new ProductCategoryDto( );
                gc2.setName( "Plan" );
                gc2.setSequenceNumber( year );
                grandChildren.add( gc2 );

                child.setProductCategories( grandChildren );

                root.getProductCategories( ).add( child );
            }

            roots.add( root );
        }
        return roots;
}

// V10 NOT WORKING (shows only the root elements)

        TreeGrid<ProductCategoryDto> treeGrid = new TreeGrid<>( );
        treeGrid.setWidth( "100%" );
        treeGrid.setHeight( null );
        add( treeGrid );

        treeGrid.addColumn( ProductCategoryDto::getName ).setHeader( "ProductCategory Name" ).setFlexGrow( 0 ).setWidth( "340px" )
                .setId( "name-column" );
        treeGrid.addColumn( ProductCategoryDto::getSequenceNumber ).setHeader( "Sequence Number" ).setFlexGrow( 0 ).setWidth( "340px" );

        List<ProductCategoryDto> roots = getRoots( );

        // method A
        treeGrid.setItems( roots, ProductCategoryDto::getProductCategories );

```

--------------------------------
IN V8 I use the code below instead of the codes below "// V10 NOT WORKING (shows only the root elements)" comment.
``
      
        TreeGrid<ProductCategoryDto> treeGrid = new TreeGrid<>( );
        treeGrid.setWidth( "100%" );
        treeGrid.setHeight( null );
        add( treeGrid );

        treeGrid.addColumn( ProductCategoryDto::getName ).setHeader( "ProductCategory Name" ).setFlexGrow( 0 ).setWidth( "340px" )
                .setId( "name-column" );
        treeGrid.addColumn( ProductCategoryDto::getSequenceNumber ).setHeader( "Sequence Number" ).setFlexGrow( 0 ).setWidth( "340px" );

        List<ProductCategoryDto> roots = getRoots( );

        // method A
        treeGrid.setItems( roots, ProductCategoryDto::getProductCategories );
``

**Comment by denis-anisimov** [comment] 2018-08-06 07:46
The code doesn't work as expected because you should use `addHierarchyColumn`  to have a column which expands hierarchical data representation in the `TreeGrid`.

So if you change the line `treeGrid.addColumn( ProductCategoryDto::getName ).setHeader( "ProductCategory Name" ).setFlexGrow( 0 ).setWidth( "340px" )
                .setId( "name-column" );` 

to 
```
treeGrid.addHierarchyColumn(ProductCategoryDto::getName)
                .setHeader("ProductCategory Name").setFlexGrow(0)
                .setWidth("340px").setId("name-column");
```
then this column shows an icon which can be used to expand tree item.

So the API in V10 is not the same as in V8.
So this is technically not a bug.
But I agree that this is confusing behavior since it's not obvious that you have to call `addHierarchyColumn` to get tree structure visible.

I'm closing this ticket since this is not a bug but could you please create another ticket to improve the `TreeGrid`  behavior so that it should be clear then you need to call `addHierarchyColumn` to be able to use hierarchy?
I think we should at least mention this in javadocs somehow and may be improve API or runtime behavior (so that either warning or something happens it there is no any hierarchy column).

**Closed by denis-anisimov** 2018-08-06 07:46 UTC

**Comment by ugurdoksan** [comment] 2018-08-07 09:12
This solution solved my problem, thank you very much...
