### ISSUE TITLE
Grid components are not always rendered immediately

### ISSUE THREAD

**Issue by drewharvey** [vaadin/vaadin-grid-flow#557] opened 2019-02-22 22:50 UTC
Vaadin 10.0.11
Chrome

Some times components in Grid cells do not get rendered until another action takes place.  It seems that it is usually the first two cells that do not render.  Even after the user performs an action on the grid (selects another visible component in the grid) the missing components render but the row height is not adjusted to fit.  

I've attached an example of a situation where this issue is reproducible 100% of the time.  I'm changing the number of items in the Grid's internal list from 0 to 1 to 2.  Once there are 2 items, you can see some of the ComboBox components do not render immediately.

![grid-component-rendering-issue](https://user-images.githubusercontent.com/2496955/53275771-3488c280-36b1-11e9-85f4-341712111844.gif)

**Comment by marcelo107** [comment] 2019-02-25 14:49
It is not necesssarily always the first two cells. In my case the component column is the last cell of the row. It also does not render until another action takes place.

**Comment by retomerz** [comment] 2019-02-26 12:23
We run in the same problem. We use Vaadin 13 beta 1

**Comment by anasmi** [comment] 2019-02-26 13:44
@marcelo107 @retomerz could try to update to beta2. Is issue still reproducible there?

**Comment by ujoni** [comment] 2019-02-26 15:18
I tried the following snippet 

```java
@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        final List<Thing> things = new ArrayList<>();
        things.add(thingWithValues(8));

        ListDataProvider<Thing> provider = new ListDataProvider<>(things);

        Grid<Thing> thingsGrid = new Grid<>();
        thingsGrid.setDataProvider(provider);

        thingsGrid.addColumn(new ComponentRenderer<>(thing -> new ComboBox<>(thing.getValues1().size() + " items", thing.getValues1()))).setHeader("1/3 items");
        thingsGrid.addColumn(new ComponentRenderer<>(thing -> new ComboBox<>(thing.getValues2().size() + " items", thing.getValues2()))).setHeader("2/3 items");
        thingsGrid.addColumn(new ComponentRenderer<>(thing -> new ComboBox<>(thing.getValues3().size() + " items", thing.getValues3()))).setHeader("3/3 items");

        Button button = new Button("Add row", event -> {
            things.add(thingWithValues(11));
            provider.refreshAll();
        });

        add(new Paragraph(Version.getFullVersion()), thingsGrid, button);
    }
    
    private static class Thing {
        private List<String> values;
        private int third;
        Thing(List<String> values) {
            this.values = values;
            third = (int)Math.ceil(values.size() / 3.0);
        }

        List<String> getValues1() { return values.subList(0, third); }

        List<String> getValues2() { return values.subList(third, 2 * third); }

        List<String> getValues3() { return values.subList(2 * third, values.size()); }
    }

    private static Random r = new Random();
    private static Thing thingWithValues(int count) {
        return new Thing(IntStream.range(0, count).map(i -> r.nextInt()).mapToObj(Integer::toHexString).collect(Collectors.toList()));
    }
}
```

and I was able to replicate the problem using Vaadin `10.0.11` but not with Vaadin `13.0.0.beta2` nor Vaadin `13.0.0.beta1`. @marcelo107, @retomerz what are the specific conditions in which you face this problem?

**Comment by marcelo107** [comment] 2019-02-26 20:39
@anasmi, strangely enough I can't reproduce the issue any more. I tried with Vaadin 12.0.7, 13.0.0.beta1 and 13.0.0.beta2 and they all seem to work now (tried with Chrome and FF). @ujoni my use case basically envolves uploading a file and then the file is presented in the grid with one of the columns as a button that downloads said file.
![selecao_391](https://user-images.githubusercontent.com/13228078/53444583-56ee4900-39ed-11e9-9075-c3de205f6e6c.png)

**Comment by drewharvey** [comment] 2019-02-26 21:21
Just updated to the latest Chrome and I can still reproduce this 100% of the time with my original example.

**Comment by Legioth** [comment] 2019-02-27 14:26
> Just updated to the latest Chrome and I can still reproduce this 100% of the time with my original example.

Could you please share a reduced test case so that we can actually reproduce the issue.

**Comment by drewharvey** [comment] 2019-02-27 18:08
I am able to reproduce the issue with the following code.  I also tried the same thing by using Grid.addComponentColumn and had the same result (non-rendered ComboBoxes).  Seems that using different browser window widths affects which components do/don't render.  I will post an image showing the difference.

`import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.data.renderer.ComponentRenderer;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.veracyte.entity.veralis.data.lab.afirma.NoduleLocation;
import com.veracyte.entity.veralis.data.lab.afirma.ReceivedOrder;
import com.veracyte.ui.views.MainView;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;

@Route(value = "test", layout = MainView.class)
@PageTitle("Grid Rendering Issue")
public class IssueExample extends VerticalLayout {

    private List<Item> items = new ArrayList<>();

    public IssueExample() {

        Grid<Item> grid = new Grid<>();
        grid.setItems(items);

        // ID
        grid.addColumn(new ComponentRenderer<>(ComboBox<String>::new, (comboBox, nodule) -> {

        })).setHeader("ID");

        // Order
        grid.addColumn(new ComponentRenderer<>(ComboBox<ReceivedOrder>::new, (comboBox, nodule) -> {

        })).setHeader("Order");

        // Location
        grid.addColumn(new ComponentRenderer<>(ComboBox<NoduleLocation>::new, (comboBox, nodule) -> {

        })).setHeader("Location");


        // Number of items input

        TextField numItems = new TextField("Num Items");
        numItems.addValueChangeListener(e -> {
            int num = 0;
            try {
                if (e.getValue() != null && !e.getValue().isEmpty()) {
                    num = Integer.parseInt(e.getValue());
                }
            } catch (Exception ex) {

            }
           items.clear();
            IntStream.rangeClosed(1, num).forEach(i -> {
                items.add(new Item(i+"id", i+"location"));
            });

            grid.getDataProvider().refreshAll();
        });

        add(numItems, grid);
    }

    public class Item {
        String id;
        String location;
        public Item(String id, String location) {
            this.id = id;
            this.location = location;
        }
    }
}`

**Comment by drewharvey** [comment] 2019-02-27 18:17
Full screen width:
![grid-rendering-issue-full-screen](https://user-images.githubusercontent.com/2496955/53512789-839b7280-3a78-11e9-895f-5d3fd3aace79.gif)

70% screen width:
![grid-rendering-issue-70-width](https://user-images.githubusercontent.com/2496955/53512792-87c79000-3a78-11e9-9223-35b3630ec9d3.gif)

**Comment by Klaudeta** [comment] 2019-03-01 21:12
So far I can isolate the issue to be present only with comboboxes and the cause of it happening is a combination of the [#5025](https://github.com/vaadin/flow/issues/5025) and a substantial change in vaadin-combo-box(web) done in [v4.2.1](https://github.com/vaadin/vaadin-combo-box/releases/tag/v4.2.1)

[#5025](https://github.com/vaadin/flow/issues/5025) is fixed in [ flow v1.4.0](https://github.com/vaadin/flow/releases/tag/1.4.0)

The fix done for [#5025](https://github.com/vaadin/flow/issues/5025) does not work for vaadin-combo-box (web) prior to version v4.2.1

So the combination that's  working is having both [ flow v1.4.0](https://github.com/vaadin/flow/releases/tag/1.4.0)   and  vaadin-combo-box (web) version v4.2.1 (or greater).

This combination is found in Vaadin 12.0.7, Vaadin 13.0.0.beta2 and  13.0.0.beta3 the versions where I can't reproduce the issue.

**Comment by Klaudeta** [comment] 2019-03-04 08:22
The changes of vaadin-combo-box on [v4.2.1](https://github.com/vaadin/vaadin-combo-box/releases/tag/v4.2.1), specifically this change [6a94726](https://github.com/vaadin/vaadin-combo-box/commit/6a94726147c12c1ca2e90f8f0a85bb22677c66b5) has decreased considerably the rendering time of the combobox. I guess this allows the fix done for [#5025](https://github.com/vaadin/flow/issues/5025) to be applied also on the comb-box making it to be rendered once the notifyResize is called inside `requestAnimationFrame`

**Comment by OlliTietavainenVaadin** [comment] 2019-03-14 07:37
Minimal example, tested on Vaadin 13.0.1 with Windows 10 on Chrome, Edge and FF:
```java
public class MainLayout extends VerticalLayout {

    protected Grid<String> grid;

    public MainLayout() {
        setSizeFull();
        grid = new Grid<String>();
        grid.addColumn(new ComponentRenderer<>(item -> new Span("test"))).setHeader("Test");
        grid.setItems("Foo");
        add(grid);
        Button btn = new Button("Add new column with Span ComponentRenderer");
        btn.addClickListener(e -> {
            grid.addColumn(new ComponentRenderer<>(item -> new Span("test new"))).setHeader("new column");
        });
        add(btn);
    }
}
```

**Comment by pleku** [comment] 2019-03-14 08:30
The fix will land to Flow 1.0.10 when it is released

**Closed** 2019-03-14 08:29 UTC
Labels: BFP, bug, components, in review unscoped

**Comment by Klaudeta** [comment] 2019-03-14 08:34
@OlliTietavainenVaadin  I think your example it's not related to the issue in here. The original issue here is affected/reproducible only for Chrome 72. In the original issue the component is actually being added into the dom but it is not rendered and it is happening when new rows are being added into the grid.
While in you example the issue is happening when you are added new columns and by expecting you can see that the component of the last column is not actually being added at all on the dom when the last column is added.

I think you have to open a new issue for the example you provided.

**Comment by OlliTietavainenVaadin** [comment] 2019-03-14 09:28
Thanks @Klaudeta , I created https://github.com/vaadin/vaadin-grid-flow/issues/587

**Comment by rthadhani** [comment] 2019-05-20 09:14
Adding my issue in the same thread so that it gets tracked and anyone facing the same issue can help.

Issue : Two columns in the vaadin grid render after some period of time. The columns consist of the link.
I have used Polymer 2.0 and done minification in es6 .  If I remove minification the columns render properly and on time , but when I add it again the columns take time to render. One thing I noticed is ; the columns are there on the DOM but not render on the webpage.

Vaadin-grid version : 5.3.3

Code -

<vaadin-grid-column width="[[column.width]]" resizable slot="1">
                                <template class="header">
                                    <div class="header">Action</div>
                                </template>
                                <template>                                   
                                    <span column>
                                        <a data-column-name$="action" title="Enroll" data-row-detail$="{"vId":"72129229659570176","customerName":"Anant Bandewar","phoneNumber":"8600384240","emailId":"bandewar_anant@mailinator.com","shortLocation":", , ","fullLocation":", , ","createdDate":"5/15/2019 7:26:27 AM","agencyName":"Top Travel","agencyId":"7086","agencyShortLocation":"Pompano Beach, VE, US","agencyPhone":"(388)-906-4246","preferredAgentName":"Jesse Cunningham","agentId":"54426854989234177","agentEmail":"jesse.garcia@travelleaders.com","membershipType":"Paid","membershipStatus":"Active","enrollmentDate":"May 15, 2019","memStartDate":"-","memEndDate":"-","memCode":"","action":"Assign","dateOfBirth":null,"gender":null,"address":{"id":"1","addressLine1":"","addressLine2":"","city":"","state":"","country":"","zipCode":""},"name":{"title":null,"prefix":null,"firstName":"Anant","middleName":null,"lastName":"Bandewar","suffix":null},"phone":{"value":"8600384240","isDefault":true,"id":"1"},"membershipDetail":{"category":"Travel","providerName":"American Express","providerCode":"AMEX","type":"Paid","status":"Active","enrollmentDate":"May 15, 2019","startDate":"-","endDate":"-","code":"","itemCode":"AMEX-TTC"},"isPreferredAgentPresent":false,"isAgentICCustomer":false,"identitySettingsId":"72129229659570177","isCardAcquisitionEmailSent":true,"referredBy":"AMEX Agent","username":"bandewar.anant@mailinator.com"}" href="javascript:void(0);"
                   on-tap="__linkClicked">Assign</a>
                                    </span>
                                </template>
                            </vaadin-grid-column>
