### ISSUE TITLE
Basic grid does not show up at all

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid-flow#57] opened 2018-01-08 14:01 UTC
```
@Route("")
public class ComponentsView extends VerticalLayout {

	public ComponentsView() {
		Grid<String> grid = new Grid<>();
		grid.addColumn(string -> string);

		grid.setItems("First row", "Second row");

	}

}
```

Expected:
A grid with one column and two rows is shown

Actual:
Nothing is shown (grid has size 0x400)

**Comment by gilberto-torrezan** [comment] 2018-01-08 14:03
Duplicate of https://github.com/vaadin/vaadin-grid-flow/issues/11

**Closed by gilberto-torrezan** 2018-01-08 14:03 UTC

**Comment by pleku** [comment] 2018-01-08 14:06
> Nothing is shown (grid has size 0x400)

Is it 0 width or height ?

**Comment by Artur-** [comment] 2018-01-08 14:17
Width
