### ISSUE TITLE
Grid doesn't render Checkbox in ComponentRenderer properly

### ISSUE THREAD

**Issue by dg0s** [vaadin/vaadin-grid-flow#512] opened 2019-02-07 19:13 UTC
Grid seems not render the checkbox component properly when using a ComponentRenderer.

Vaadin 12.0.5
OS X 10.14.2
Chrome 71.0.3578.98

![checkbox_bug](https://user-images.githubusercontent.com/2262980/52436466-40e71a00-2b0c-11e9-8092-07973e42d05f.gif)

```
@Route
@PWA(name = "Project Base for Vaadin Flow with Spring", shortName = "Project Base")
public class MainView extends VerticalLayout {

    private Grid<Person> grid;

    private List<Person> persons = new ArrayList<>();
    private List<Person> actors = new ArrayList<>();
    private int count = 0;

    class Person {
        private String name;
        private Boolean enabled;

        public Person(String name, Boolean enabled) {
            this.name = name;
            this.enabled = enabled;
        }

        public String getName() {
            return name;
        }

        public Boolean getEnabled() {
            return enabled;
        }

        public void setEnabled(Boolean enabled) {
            this.enabled = enabled;
        }
    }

    public static class CheckboxRenderer<T> extends ComponentRenderer<Checkbox, T> {
        public CheckboxRenderer(ValueProvider<T, Boolean> getter, Setter<T, Boolean> setter) {
            super(Checkbox::new, (checkbox, entity) -> {
                checkbox.setValue(getter.apply(entity));
                checkbox.addValueChangeListener(v -> setter.accept(entity, v.getValue()));
            });
        }

        public static <T> CheckboxRenderer<T> of(ValueProvider<T, Boolean> getter, Setter<T, Boolean> setter) {
            return new CheckboxRenderer<>(getter, setter);
        }
    }

    public MainView(@Autowired MessageBean bean) {

        persons.add(new Person("John Wick", true));
        persons.add(new Person("Constantine", true));
        persons.add(new Person("Mr. Anderson", true));


        grid = new Grid<>();
        grid.addColumn(Person::getName);
        grid.addColumn(CheckboxRenderer.of(Person::getEnabled, Person::setEnabled));


        Button btn = new Button("Add", this::addItem);

        add(btn, grid);
    }

    private void addItem(ClickEvent<Button> buttonClickEvent) {
        if (count == persons.size()) {
            count = 0;
            actors = new ArrayList<>();
            grid.setItems(actors);
        }
        actors.add(persons.get(count++));
        grid.setItems(actors);
    }

}
```

**Comment by TatuLund** [comment] 2019-02-11 11:32
This is probably duplicate of https://github.com/vaadin/flow/issues/5025

**Comment by pleku** [comment] 2019-02-12 06:40
Closing as duplicate of vaadin/flow#5025

**Closed by pleku** 2019-02-12 06:40 UTC
