### ISSUE TITLE
Tree Grid hierarchy is broken when dataProvider is refreshed from another view

### ISSUE THREAD

**Issue by onuridrisoglu** [vaadin/vaadin-grid-flow#603] opened 2019-03-25 09:56 UTC
I have a use case, where user works in two views, the first view has a tree grid, and in second view user updates the content of the tree grid. If the views are in different windows and both are visible, it works fine. However, if these views are opened in different tabs, TreeGrid loses hierarchy after user returns to the first view.

Here is a sample code to reproduce the issue, (MainView has Push annotation).
**First View:**
	
	public MainView() {
		subscribe(); // Subscribes to Event Bus
		provider = new SampleTreeDataProvider();
		TreeGrid<Bean> treeGrid = new TreeGrid<>(provider);
		treeGrid.addHierarchyColumn(Bean::getValue).setHeader("Bean");
		Anchor anchor = new Anchor("new-page", "Open New Page");
		anchor.setTarget("_blank");
		add(treeGrid, anchor);
	}

	@Subscribe
	private void processRefresh(RefreshEvent evt) {
		provider.refreshAll();
	}

**Data Provider:**

	private Bean root;

	public SampleTreeDataProvider() {
		root = new Bean("0");
		root.setChildren(generateChildren(root));
		root.getChildren().forEach(bean -> bean.setChildren(generateChildren(bean)));
	}

	@Override
	public int getChildCount(HierarchicalQuery<Bean, SerializablePredicate<Bean>> query) {
		if (query.getParent() == null) {
			return 1;
		} else {
			return query.getParent().getChildren().size();
		}
	}

	@Override
	public boolean hasChildren(Bean item) {
		return item.getChildren() != null && !item.getChildren().isEmpty();
	}

	@Override
	protected Stream<Bean> fetchChildrenFromBackEnd(HierarchicalQuery<Bean, SerializablePredicate<Bean>> query) {
		if (query.getParent() == null) {
			return Stream.of(root);
		} else {
			return query.getParent().getChildren().stream();
		}
	}

	private List<Bean> generateChildren(Bean bean) {
		String base = bean != null ? bean.getValue() + "." : "";
		List<Bean> beans = new ArrayList<>();
		for (int i = 0; i < 5; i++) {
			beans.add(new Bean(base + i));
		}
		if (bean != null) {
			bean.setChildren(beans);
		}
		return beans;
	}

**Second View:**

	public NewPage() {
		subscribe();
		Button button = new Button("Refresh");
		button.addClickListener(evt -> postEvent(new RefreshEvent()));
		add(button);
	}

**Screen Recording:**
![tree-hierarchy-error](https://user-images.githubusercontent.com/33827141/54910176-77c69300-4ef4-11e9-93cb-857a75bf8225.gif)

Vaadin version : 13.0.1
Browser : Chrome Version 72

**Comment by ZheSun88** [comment] 2019-03-25 13:39
Hi @onuridrisoglu , Thanks for reporting this. but could you test with Chrome Version 73 for us, too?

**Comment by onuridrisoglu** [comment] 2019-03-25 13:53
yes, the result is the same also for Chrome Version 73

**Comment by pekam** [comment] 2019-07-01 09:47
Looks like the underlying cause of this bug is the same as for #589. I was able to reproduce the issue without the fix #688, but not by including this fix.

The fix is released in `vaadin-grid-flow` 4.0.1, which will be included in Vaadin 14.0.0.rc3.

If I'm mistaken and the issue is still present with those releases, we can re-open the issue.

**Closed by pekam** 2019-07-01 09:47 UTC
Labels: BFP, bug, components
