### ISSUE TITLE
Updating of 'disabled' property in grid-column headers

### ISSUE THREAD

**Issue by KasparScherrer** [vaadin/vaadin-grid-flow#814] opened 2019-11-04 15:48 UTC
In Vaadin, the disabled property is inherited from parent components. When a layout is disabled, all components within are getting disabled as well. This also applies to Grids - any Component within a Grid is disabled when the grid itself is disabled.

However, I have found that grid column headers are handled differently (or just have a bug right now). I have one Input Field in each column Header (TextField or ComboBox) and right after the page is loaded these input fields are correctly enabled/disabled depending on whether the grid is enabled/disabled upon page load, so this part works. But when I now disable the previously enabled Grid, these filter fields do not get disabled. The same is true vice versa - When I enable a previously disabled Grid, the filter fields still remain disabled. 

The whole disabledness-inheritance works upon page load but when updating the disabledness of a grid, grid headers do not receive that update.

Code for reproduction:
```
@Route(value = "Test")
public class TestView extends VerticalLayout implements HasUrlParameter<String> {
    private Grid<String> grid;

    public TestView(){
        Set<String> allItems = new HashSet<>();
        allItems.add("Foo");
        allItems.add("Bar");
        allItems.add("FooBar");

        grid = new Grid<>();
        Grid.Column<String> filterableColumn = grid.addColumn(String::toString);
        grid.addComponentColumn(item -> new Button("I receive updates for disabled"));

        grid.setItems(allItems);

        Button toggleDisabledForGrid = new Button("Toggle Disabled for Grid", click -> {
            grid.setEnabled(!grid.isEnabled());
        });

        TextField filterField = new TextField();
        filterField.setPlaceholder("No updates for disabled");
        filterField.setValueChangeMode(ValueChangeMode.EAGER);
        filterField.addValueChangeListener(event -> {
            ((ListDataProvider) grid.getDataProvider()).setFilter(item -> {
                return item.toString().contains(filterField.getValue());
            });
        });
        filterableColumn.setHeader(filterField);

        add(toggleDisabledForGrid, grid);
    }

    @Override
    public void setParameter(BeforeEvent beforeEvent, String urlParameter) {
        if(urlParameter.equals("disabled")){
            grid.setEnabled(false);
        }
    }
}
```
Using this code, you can go to `/Test/disabled` and see how the grid headers will never be enabled no matter how many times you toggle the disabledness by clicking the button. The opposite can also be seen: navigate to `/Test/aa` and see how the filter field is always enabled.

**Comment by KasparScherrer** [comment] 2019-11-04 16:41
This has strong ramifications in the UX. Not only can the user no longer filter the grid items, but the user doesn't even know which column is which because he doesn't see any placeholder in the filter fields.

**Comment by yuriy-fix** [comment] 2019-12-04 12:09
The root cause of the issue is coming from https://github.com/vaadin/flow/issues/7085. Have prioritised that one and closed my PR.

**Comment by yuriy-fix** [comment] 2020-01-08 09:13
Seems to be fixed via https://github.com/vaadin/flow/pull/7131

**Closed by yuriy-fix** 2020-01-08 09:13 UTC
Labels: BFP
