### ISSUE TITLE
Icons missing when using TemplateRenderer and icons

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-grid-flow#614] opened 2019-04-05 18:28 UTC
*Tested on Vaadin 13.0.3* -> only on Chrome browser. 

When using `Grid`, and adding a column with `TemplateRenderer`, and inside the template using `<iron-icon>` the resulting grid will show an empty column, but the icons will appear after hovering on them with the mouse pointer.

Here's A small gif showing the problem:

![HoverIconGridProblem](https://user-images.githubusercontent.com/28312758/55648653-446aea80-57b7-11e9-8392-dab419330f66.gif)

And here's the code to reproduce the issue:

```
@Route("")
@HtmlImport("frontend://bower_components/vaadin-icons/vaadin-icons.html")
public class MainView extends VerticalLayout {
	public MainView() {
		Grid<String> grid = new Grid<>();
		grid.addColumn(TemplateRenderer.<String>of(
				"<a href=\"https://www.google.com/search?q=[[item.id]]\" target=\"_blank\">"
				+ "<iron-icon icon=\"vaadin:edit\" style=\"color: rgb(128,0,0);\"></iron-icon></a>")
				.withProperty("id",String::length)).setHeader("Column");
		grid.setItems("1","2","3","4","5","6","7","8","9","10");
		add(grid);
    }
}
```

**Comment by pleku** [comment] 2019-04-05 19:10
This looks like yet another manifestation of the Chrome72 (and later) shadow dom regression. Can you please test with Dev and Canary channels of Chrome?

**Comment by ZheSun88** [comment] 2019-04-08 06:44
I just did a quick test with the provided code on project-base 13.0.3. 
It looks @pleku is correct. the same issue cannot be reproduced on FF or MS edge.

**Comment by web-padawan** [comment] 2020-02-14 12:54
Closing per https://github.com/vaadin/vaadin-grid-flow/issues/614#issuecomment-480390309 as  related to an old bug which was only affecting Chrome 72.

**Closed by web-padawan** 2020-02-14 12:54 UTC
Labels: Chrome, bug
