### ISSUE TITLE
Scorolling the grid creates blank spaces

### ISSUE THREAD

**Issue by vaithu** [vaadin/vaadin-grid-flow#1070] opened 2020-07-07 02:48 UTC
I'm using version 14.2.3. The Grid component uses lazy loading and while scrolling down, it creates blank spaces like below 
![image](https://user-images.githubusercontent.com/35440074/86695508-99a93380-bfda-11ea-836f-be81aabe2f53.png)
and the blank size increases if you scroll the page faster. The faster you scroll, more the blank space is.

**Comment by jcgueriaud1** [comment] 2020-07-10 16:53
It's probably the same issue as this one: https://github.com/vaadin/vaadin-grid/issues/1659

Are you using the scrollbar to scroll down?

**Comment by vaithu** [comment] 2020-07-10 19:49
Yes. Exactly it is the same issue. The item data set has 80K records and
uses lazy loading.

I used Scroller to quickly move to the 1000th item and it created the whole
page as blank.

Regards

S Kadhir

IIB Remote Support|Training|Consultation

+1(612) 305 8684

www.vaithu.com

**Comment by alvarezguille** [comment] 2020-07-14 10:10
Closing as duplicate of https://github.com/vaadin/vaadin-grid/issues/1659

**Closed by alvarezguille** 2020-07-14 10:10 UTC
