### ISSUE TITLE
Multiselect grid with callback data provider does not have a select all checkbox

### ISSUE THREAD

**Issue by eriklumme** [vaadin/vaadin-grid-flow#549] opened 2019-02-21 07:23 UTC
`Grid 2.1.5`

### Code example

    Grid<String> grid = new Grid<>();
    grid.addColumn(String::toString).setHeader("Header");
    grid.setSelectionMode(Grid.SelectionMode.MULTI);

    List<String> items = Arrays.asList("One", "Two", "Three");
    grid.setDataProvider(DataProvider.fromCallbacks(
            query -> items.stream().skip(query.getOffset()).limit(query.getLimit()),
            query -> items.size()
    ));
    add(grid);

### Expected result

The grid has a checkbox for selecting all rows

### Actual results

The checkbox for selecting all has the `hidden` attribute and is not displayed

**Comment by heruan** [comment] 2019-02-21 07:26
I confirm this. Plus, if I have no header row and I use multi-select, an empty header row is shown; this shouldn't happen: if I have no headers, I also don't want the "check all" checkbox.

**Comment by eriklumme** [comment] 2019-02-21 07:29
Related to that, here's what a multiselect grid with no columns and no items looks like

![screen shot 2019-02-21 at 9 28 37](https://user-images.githubusercontent.com/29859656/53151171-20629980-35bb-11e9-95de-1cf8ccf55c0a.png)

**Comment by Legioth** [comment] 2019-02-21 07:40
Please create separate issues for the other things reported here. The original issue works as intended except that we might have to do something to make it easier to understand the situation.

Imagine you have a lazy loading data provider connected to a database with millions of rows. If the user would click the checkbox to select all items, the server-side logic would have to load millions of items from the database into memory so that `grid.getSelectedItems()` could contain them all. Furthermore, this needs to happen eagerly so that it can reflect the rows that were in the database at the moment when the user clicked the checkbox.

Because of the potential performance implications of loading millions of items into memory, the checkbox is by default hidden when using a data provider that doesn't already have all items loaded in memory (as indicated by `dataProvider.isInMemory()`. This behavior is configurable through `GridMultiSelectionModel::setSelectAllCheckboxVisibility`. To actually use this method, you need to do `grid.getSelectionModel()` and explicitly cast it to `GridMultiSelectionModel`.

We could consider somehow making this functionality easier to discover, but I'm not sure what that would be. One potential idea would be that `grid.asMultiSelect()` would return a custom `MultiSelectGrid<T>` class with the same `setSelectAllCheckboxVisibility` instead of the current generic `MultiSelect<Grid<T>, T>` return type.

**Comment by heruan** [comment] 2019-02-21 07:59
Thank you @Legioth for the feedback! Still, it would be useful to have the "select all" checkbox available when the grid is filtered under a configurable threshold; thanks to the API you mentions, I guess this can be easily implemented with a custom data provider!

**Comment by Legioth** [comment] 2019-02-21 08:09
That's actually how it worked in Vaadin 7. The checkbox was by default visible in grids containing less than 1000 items (if I remember correctly) and hidden in grids with more data.

That approach was quite confusing for many users since the checkbox was present during development when using a smaller database, but then mysteriously disappeared when running against a production database. For this reason, we changed the logic to be based on the type of data provider starting from Vaadin 8.

Applications can still make it available using `setSelectAllCheckboxVisibility`, but the logic for doing so is explicitly part of the application instead of depending on external circumstances.

**Comment by pleku** [comment] 2019-07-16 11:16
I don't see at the moment what else we would do for this than add better documentation or examples.

Then again, the issue description is wrong as the component works as intended, so I'm going to close this issue and _aggressively wait_ for someone to great a better one where they describe how the lacking documentation is an issue for them (or by reporting the same thing again which proves the lack of documentation).

**Closed by pleku** 2019-07-16 11:16 UTC

**Comment by fschon** [comment] 2019-07-31 06:31
I also ran into this issue without knowing why the checkbox didn't appear. I suggest adding a Java example with this behaviour in  https://vaadin.com/components/vaadin-grid/java-examples/selection

This would have made it very clear for me.
