### ISSUE TITLE
GridContextMenu is not available after remove/add grid element

### ISSUE THREAD

**Issue by dg0s** [vaadin/vaadin-grid-flow#459] opened 2018-12-10 23:16 UTC
### Description
Add a Grid with ContextMenu to a VerticalLayout. Remove all element from the VerticalLayout and add the grid again. The Grid remains perfect but the ContextMenu is not available.

### How to reproduce
```
@Route("")
@PWA(name = "Project Base for Vaadin Flow", shortName = "Project Base")
public class MainView extends VerticalLayout {

    class Sample {
        private String key;
        private String value;

        public Sample(String key, String value) {
            this.key = key;
            this.value = value;
        }

        public String getKey() {
            return key;
        }

        public String getValue() {
            return value;
        }
    }

    private VerticalLayout content = new VerticalLayout();
    private Grid<Sample> grid;

    public MainView() {

        Button add = new Button("Add",e->buildGrid());
        Button remove = new Button("Remove",e->replace());
        add(new HorizontalLayout(add,remove));
        add(content);
        buildGrid();
    }

    private void replace(){
        content.removeAll();
        content.add(new Label("No Data"));
    }

    private void buildGrid(){
        content.removeAll();
        if(grid == null){
            grid = new Grid<>();
            grid.addColumn(Sample::getKey).setHeader("Key");
            grid.addColumn(Sample::getValue).setHeader("Value");

            List<Sample> samples = new ArrayList<>();
            samples.add(new Sample("vaadin","great"));
            grid.setItems(samples);
            grid.addContextMenu().addItem("Item",e->Notification.show("Vaadin is great!"));
        }

        content.add(grid);
    }
}
```
![bug_grid](https://user-images.githubusercontent.com/2262980/49767864-217d6d80-fcd2-11e8-8451-9549dd597380.gif)

### Result
The ContextMenu should be available after add the grid again to the layout.

**Comment by dg0s** [comment] 2018-12-10 23:38
A workaround for this issue:
```
private <T> void workaroundContextMenu(Grid<T> grid, GridContextMenu<T> contextMenu) {
        grid.addAttachListener(e -> {
            Element targetElement = contextMenu.getTarget().getElement();
            e.getUI().getPage().executeJavaScript("window.Vaadin.Flow.contextMenuConnector.init($0)", targetElement);
            contextMenu.setTarget(grid);
        });
    }
```

**Comment by pekam** [comment] 2019-06-25 12:02
This is a duplicate of vaadin/vaadin-context-menu-flow#47 and vaadin/vaadin-context-menu-flow#49. The fix will be included in Vaadin 14. I've tested with 14.0.0.beta2 that it works also with Grid.

**Closed by pekam** 2019-06-25 12:02 UTC
Labels: bug
