### ISSUE TITLE
Vaadin Grid in UIScope component like dead when routing back

### ISSUE THREAD

**Issue by cwrsimon** [vaadin/vaadin-grid-flow#615] opened 2019-04-05 19:41 UTC
I have an instance of a Vaadin grid in a Spring Component with UIScope annotation. The component is part of a Spring Boot application with numerous other UIScope components. All components have a Route annotation. Hence, it shall be possible for the user to navigate from component to component and eventually return to previously visited components. 
If I don't scroll the grid with many entries, go someplace else and return lateron (either using a router link or the browser's back button), it will be in the state that I left it in and will be fully functional. But here comes the issue: If I scroll down in the grid, go someplace else and return, the grid will be dead. No single row will be displayed, no single column can be seen, it is practically dead. Only remedy: Hitting the reload button.

Here is a sample component that can be tested with 10.0.12 and 13.0.3:
```
@SpringComponent
@Route("biggrid")
@UIScope
public class BigGrid extends VerticalLayout {
    
    private final ArrayList<MyRow> items;

    private class MyRow {

        private int id;

        public MyRow(int i) {
            this.id = i;
        }

        public int getId() {
            return id;
        }

    }
    
    public BigGrid() {
        setHeight("100%");
        setWidth("100%");
        this.items = new ArrayList<>();
        for (int i = 0; i < 5000; i++) {
            items.add(new MyRow(i));
        }
    }

    @PostConstruct
    public void init() {
        
        var bigGrid = new Grid<MyRow>();
        bigGrid.setHeight("500px");
        bigGrid.setWidth("100%");
                
        bigGrid.setDataProvider(DataProvider.ofCollection(this.items));

        var colId = bigGrid.addColumn(MyRow::getId);
 
        add(new RouterLink("Go somewhere else", Other.class));
        add(bigGrid);
    }
}
```

**Comment by Legioth** [comment] 2019-04-08 10:51
Duplicate of #539

**Closed by Legioth** 2019-04-08 10:51 UTC
Labels: bug, data provider, spring
