### ISSUE TITLE
Grid edit mode doesn't work after remove element

### ISSUE THREAD

**Issue by dg0s** [vaadin/vaadin-grid-flow#811] opened 2019-10-31 22:02 UTC
**Steps to reproduce.**

1. Add a grid in edit mode to a VerticalLayout.
2. Remove all components from VerticalLayout.
3. Add a grid again to a VerticalLayout.

**Observed behavior:**
No child node found ...

![bug1](https://user-images.githubusercontent.com/2262980/67989192-ec4f7600-fc29-11e9-8d09-8dd7c66317e3.gif)

**Expected behavior:**
The edit mode should work as expected.

**Example:**
````
@Route("")
public class View extends Div {
    final VerticalLayout verticalLayout = new VerticalLayout();

    public View() {
        add(verticalLayout);

        final Label label = new Label("Label");
        final TextField textField = new TextField();
        final CustomGrid customGrid = new CustomGrid();

        final Button change = new Button("CHANGE", e -> {
            final int count = verticalLayout.getElement().getChildCount();
            verticalLayout.removeAll();
            if (count != 2) {
                verticalLayout.add(label, textField);
            } else {
                verticalLayout.add(customGrid);
            }
        });

        add(change);

        verticalLayout.add(label, textField);
    }

    public class CustomGrid extends VerticalLayout {
        List<Person> persons = new ArrayList<Person>() {{
            add(new Person("John"));
            add(new Person("Mike"));
        }};

        public CustomGrid() {
            Grid<Person> grid = new Grid<>();
            grid.setItems(persons);
            final Grid.Column<Person> firstNameColumn = grid.addColumn(Person::getName).setHeader("Name");
            add(grid);

            Binder<Person> binder = new Binder<>(Person.class);
            Editor<Person> editor = grid.getEditor();
            editor.setBinder(binder);
            editor.setBuffered(true);

            Div validationStatus = new Div();
            validationStatus.setId("validation");

            TextField firstNameField = new TextField();
            binder.forField(firstNameField)
                    .withValidator(new StringLengthValidator("First name length must be between 3 and 50.", 3, 50))
                    .withStatusLabel(validationStatus).bind("name");
            firstNameColumn.setEditorComponent(firstNameField);

            Collection<Button> editButtons = Collections
                    .newSetFromMap(new WeakHashMap<>());

            Grid.Column<Person> editorColumn = grid.addComponentColumn(person -> {
                Button edit = new Button("Edit");
                edit.addClassName("edit");
                edit.addClickListener(e -> {
                    editor.editItem(person);
                    firstNameField.focus();
                });
                edit.setEnabled(!editor.isOpen());
                editButtons.add(edit);
                return edit;
            });

            editor.addOpenListener(e -> editButtons.stream()
                    .forEach(button -> button.setEnabled(!editor.isOpen())));
            editor.addCloseListener(e -> editButtons.stream()
                    .forEach(button -> button.setEnabled(!editor.isOpen())));

            Button save = new Button("Save", e -> editor.save());
            save.addClassName("save");

            Button cancel = new Button("Cancel", e -> editor.cancel());
            cancel.addClassName("cancel");

            Div buttons = new Div(save, cancel);
            editorColumn.setEditorComponent(buttons);

        }
    }

    public class Person {
        private String name;

        public Person(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }
}

````

**Comment by DiegoCardoso** [comment] 2019-11-25 15:42
Hello, @dg0s 

After investigating the reason behind this bug, we could find that there's one issue at the snippet you provided that was causing this weird behavior.

When defining the column where the buttons are attached to, the code adds the reference to each button to a `Collection` in order to use it later to enable/disable them when the Grid is editing an item.

The issue here is that each time the Grid is reattached (or, in case when the row is discarded from memory), the component provider is called again, thus a new button is created. The `editButtons` collection, though, still keeps the reference to the old buttons first created, and at the callback of `Editor#addOpenListener`, `button.setEnabled()` is trying to perform an action to an element that no longer exits on the client, and then the error occurs.

In order to fix this and keep the expected behavior, it is needed to keep the `editButton` collection synched with which is actually rendered on the client. It can be done by listening to attach/detach events on the `Button`, like so:

```diff
Grid.Column<Person> editorColumn = grid.addComponentColumn(person -> {
    Button edit = new Button("Edit");
    edit.addClassName("edit");
    edit.addClickListener(e -> {
        editor.editItem(person);
        firstNameField.focus();
    });
    edit.setEnabled(!editor.isOpen());
-   editButtons.add(edit);
+	edit.addAttachListener(e -> editButtons.add(edit));
+	edit.addDetachListener(e -> editButtons.remove(edit));
    return edit;
});
```

That way, `editButtons` will be updated based on each `Button` lifecycle.

**Comment by DiegoCardoso** [comment] 2019-11-28 13:49
Closing, but let us now if this issue needs to be opened again.

**Closed by DiegoCardoso** 2019-11-28 13:49 UTC
Labels: BFP
