### ISSUE TITLE
Shift+click and ctrl+click multi-selection-by-keyboard missing in TreeGrid

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-grid-flow#790] opened 2019-10-14 10:17 UTC
TreeGrid lacks shift+click and ctrl+click multi-selection capabilities. As a workaround I've implemented the following code, however the code is not optimal since it fetches data from the DataProvider as it computes the range of items to be selected in the TreeGrid.

**Comment by mvysny** [comment] 2019-10-14 10:17
```java
/**
 * Iterates a tree structure lazily. The {@link #childrenProvider} is consulted
 * for a list of children for every item traversed. Preorder depth-first: first the node, then its descendants,
 * then its next sibling.
 * @author mavi
 */
public class PreorderTreeIterator<T> implements Iterator<T> {

    @NotNull
    private final Deque<T> queue;
    @NotNull
    private final Function<T, List<T>> childrenProvider;

    public PreorderTreeIterator(@NotNull T root,
                                @NotNull Function<T, List<T>> childrenProvider) {
        this.queue = new LinkedList<>(Arrays.asList(root));
        this.childrenProvider = childrenProvider;
    }

    @Override
    public boolean hasNext() {
        return !queue.isEmpty();
    }

    @Override
    public T next() {
        if (!hasNext()) throw new NoSuchElementException();
        final T result = queue.pop();
        final List<T> children = childrenProvider.apply(result);
        for (int i = children.size() - 1; i >= 0; i--) {
            queue.push(children.get(i));
        }
        return result;
    }
}

/**
 * Iterates the items in a Grid in exactly the same order as they appear
 * in the Grid. Children of collapsed nodes are not returned.
 * @author mavi
 */
public class TreeGridRows<T> implements Iterable<T> {

    @NotNull
    private final TreeGrid<T> treeGrid;

    public TreeGridRows(@NotNull TreeGrid<T> treeGrid) {
        this.treeGrid = treeGrid;
    }

    @NotNull
    private List<T> getChildrenOf(T item) {
        if (treeGrid.isExpanded(item)) {
            return treeGrid.getDataProvider()
                    .fetchChildren(new HierarchicalQuery<>(null, item))
                    .collect(Collectors.toList());
        } else {
            return Collections.emptyList();
        }
    }

    @NotNull
    private Stream<T> itemSubtreeStream(T item) {
        final Iterable<T> iterable = () -> new PreorderTreeIterator<>(item, it -> getChildrenOf(it));
        return StreamSupport.stream(iterable.spliterator(), false);
    }

    @NotNull
    private Stream<T> getRootItems() {
        return treeGrid.getDataProvider()
                .fetch(new HierarchicalQuery<>(null, null));
    }

    @NotNull
    public Stream<T> stream() {
        return getRootItems()
                .flatMap(it -> itemSubtreeStream(it));
    }

    @NotNull
    @Override
    public Iterator<T> iterator() {
        return stream().iterator();
    }
}

/**
 * Updates selection based on item clicks. Handles Shift+Item click correctly.
 * @author mavi
 */
public class TreeGridItemClickSelectionUpdater<T> implements ComponentEventListener<ItemClickEvent<T>> {
    private final TreeGrid<T> treeGrid;
    private T lastItemClicked = null;

    public TreeGridItemClickSelectionUpdater(TreeGrid<T> treeGrid) {
        this.treeGrid = treeGrid;
    }

    private void toggleSelection(T item) {
        if (treeGrid.asMultiSelect().isSelected(item)) {
            treeGrid.asMultiSelect().deselect(item);
        } else {
            treeGrid.asMultiSelect().select(item);
        }
    }

    @Override
    public void onComponentEvent(ItemClickEvent<T> event) {
        if (event.isCtrlKey()) {
            // toggle individual item selection
            lastItemClicked = event.getItem();
            toggleSelection(lastItemClicked);
        } else if (event.isShiftKey()) {
            // mass-selection with shift key
            if (lastItemClicked == null || Objects.equals(lastItemClicked, event.getItem())) {
                treeGrid.asMultiSelect().select(event.getItem());
                lastItemClicked = event.getItem();
            } else {
                // shift-click, select a range of items
                boolean inRange = false;
                for (T row : new TreeGridRows<T>(treeGrid)) {
                    final boolean isSelectionEndpoint = Objects.equals(row, event.getItem()) || Objects.equals(row, lastItemClicked);
                    if (inRange || isSelectionEndpoint) {
                        treeGrid.asMultiSelect().select(row);
                    }
                    if (isSelectionEndpoint) {
                        inRange = !inRange;
                        if (!inRange) {
                            // no need to go further, bail out
                            break;
                        }
                    }
                }
            }
        } else {
            // single selection with simple click
            lastItemClicked = event.getItem();
            treeGrid.asMultiSelect().setValue(Collections.singleton(lastItemClicked));
        }
    }
}
```

To use this:

```java
treeGrid.addItemClickListener(new TreeGridItemClickSelectionUpdater<>(this));
// shift+click selects text in the Grid, disable that
treeGrid.getElement().getStyle().set("user-select", "none");
```

**Comment by web-padawan** [comment] 2020-02-20 17:42
Closing as duplicate of #196.

**Closed by web-padawan** 2020-02-20 17:42 UTC
