### ISSUE TITLE
Grid has 2px height in Firefox/Edge

### ISSUE THREAD

**Issue by steffen-harbich-itc** [vaadin/vaadin-grid-flow#276] opened 2018-07-23 10:55 UTC
Please see my Stackoverflow question: https://stackoverflow.com/questions/51443246
The minimal example is referenced there. Height of the Grid component is always 2px in Firefox althought "height: 200px" is set for the element.

Vaadin flow version 10.0.1

**Comment by pekam** [comment] 2018-07-23 12:30
Hi!
I'm closing this issue as a duplicate of https://github.com/vaadin/flow/issues/4364
Thanks for reporting and the additional details!

**Closed by pekam** 2018-07-23 12:30 UTC
