### ISSUE TITLE
Component renderers not always render

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-grid-flow#937] opened 2020-03-24 15:17 UTC
I'm using component renderers for `Grid` and when scrolling, some items are not rendered at all.

<img width="1160" alt="Screenshot 2020-03-24 at 16 15 48" src="https://user-images.githubusercontent.com/851745/77442679-dade5480-6dea-11ea-872f-717976e0886b.png">

I'm unable to test or replicate this, and unfortunately, it's affecting production.

Platform is 14.1.20

**Comment by heruan** [comment] 2020-04-17 14:57
I see this has been transferred to Flow Grid. So it's not a renderer issue, but a Grid itself?

**Comment by heruan** [comment] 2020-04-20 12:39
Any update on this?

**Comment by tomivirkki** [comment] 2020-04-20 12:49
Hi @heruan Not sure yet whether it's a Grid or a Renderer issue. This is currently marked as a high priority and we'll start investigating this most likely early next week. A minimal repro zip package would help a lot.

**Comment by heruan** [comment] 2020-04-20 14:56
I'm still trying to replicate it fully, but I'm not able yet to replicate the renderers not rendering. Attached there's a sample which uses the same components in the production app and replicates the second (unnecessary) data-provider request.

[vaadin-renderer-bug.zip](https://github.com/vaadin/vaadin-grid-flow/files/4504276/vaadin-renderer-bug.zip)

**Comment by heruan** [comment] 2020-05-14 08:52
Still no update on this? It's been quite some time. At least for the multiple fetching, which is replicated?

**Comment by rolfsmeds** [comment] 2020-05-14 10:12
This issue is in the backlog for our next sprint and is flagged as high priority, so it will be dealt with as soon as we have capacity over from even more critital bugs.

**Comment by heruan** [comment] 2020-05-18 13:36
Thanks @rolfsmeds, it's been nearly two months I've reported this and I really hope I can receive some help.

**Comment by heruan** [comment] 2020-05-22 12:59
I've an update with something I haven't noticed before and I think it's what I'm unable to replicate: renderers doesn't render when the request takes a certain time to fulfill; at first I've thought it was the database query slow, so I worked on that and optimized it (from ~2s to ~0.1s) but the issue wasn't solved. So I've observed the browser network tab and I've seen this:

<img width="609" alt="Screenshot 2020-05-22 at 14 46 41" src="https://user-images.githubusercontent.com/851745/82669652-186d2b80-9c3c-11ea-9c18-89210f50d3b3.png">

i.e. there are some requests between 2 and 5 MB and is after those requests which renderers get blank. So I've debugged the offset/limit used by the data-provider for these requests, and I've found an offset of 1 and a limit of 1500 which definitely doesn't feel right.

**Comment by tomivirkki** [comment] 2020-05-25 07:58
Hi @heruan. I'm currently debugging the disappearing content issue but also have a hard time trying to reproduce it. Any more information on how this could be produced with the example app you provided?

About the 2 page requests occurring initially: The grid pools a certain amount of DOM rows (`<tr>`) to be rotated and reused for the virtual scrolling effect. The optimal amount of physical rows is determined by the internal `<iron-list>` and it [defaults](https://github.com/PolymerElements/iron-list/blob/2.x/iron-list.html#L683) to `2 * the amount of rows you can fit into the visible viewport`. With a full-screen grid and relatively narrow row height, you can easily fit around 30 rows on the visible viewport. By the pooling logic, this resolves to 60 physical row elements being rendered to the DOM.

The default `pageSize` for grid is 50, which means that the grid will request for maximum of 50 items per data request. Since 50 < 60, one data request isn't enough to populate all the physical rows in the grid so another one is made, even if you haven't yet scrolled the grid. If you want to avoid the second data request, you could increase the page size to 100 for example `grid.setPageSize(100);`.

We could also override the default pool size to be something more meaningful like `the amount of rows you can fit into the visible viewport + 300px`, which should still provide enough buffer for a smooth virtual scrolling effect.

**Comment by heruan** [comment] 2020-05-25 08:47
Hello Tomi and thank you for the insights! Setting a page size of 100 avoided the double page request *and* also solved the issue with the renderers 🎉

I mixed up two different issues on my latest post: the request with a limit of 1500 happens with an `IronList`, not `Grid`. Also, the double request happens also with `IronList`, but there's no `setPageSize` method there.

**Comment by tomivirkki** [comment] 2020-05-25 10:32
Closing this issue for now as I can't reproduce it locally (and increasing page size fixes it for you). If you bump into this again and find a way to repro, this issue should be re-opened.

**Closed by tomivirkki** 2020-05-25 10:32 UTC
Labels: BFP, Impact: Low, Severity: Major
