### ISSUE TITLE
addComponentColumn should allow returning null values

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-grid-flow#709] opened 2019-07-11 07:22 UTC
In a use case where a grid's component column only should return a component based on a condition (e.g. return a checkbox for a specific subclass of items), there are also cases, where nothing is needed and thus nothing (= `null`)should be returned.

This is currently not possible and leads to a NullPointerException. This means, that for cases where the column should be empty, always a Span or similar needs to be created. To prevent this unneeded overhead of object creation we should simply allow here to return null as it is with other API (e.g. class name generator).

**Comment by pekam** [comment] 2019-10-03 10:07
Closing as a duplicate of #593

**Closed by pekam** 2019-10-03 10:07 UTC
