### ISSUE TITLE
DatePicker in Grid doesn't show in first row

### ISSUE THREAD

**Issue by firestormdong** [vaadin/vaadin-grid-flow#570] opened 2019-03-06 00:02 UTC
Not sure if related to https://github.com/vaadin/flow/issues/5025
I'm using vaadin 12.0.7
Here's my code:
```java
        Grid<LocalDate> grid = new Grid<>();
        grid.addColumn(LocalDate::toString).setHeader("Simple Column");
        grid.addComponentColumn(value -> {
            DatePicker datePicker = new DatePicker();
            datePicker.setValue(value);
            return datePicker;
        }).setHeader("Component Column");
        grid.setItems(
                LocalDate.of(2019, 1, 1),
                LocalDate.of(2019, 2, 2),
                LocalDate.of(2019, 3, 3)
        );
```
The screenshot in latest Chrome:
![image](https://user-images.githubusercontent.com/20729067/53845975-fc5e6b00-3f5f-11e9-89b6-0b91bf74b201.png)

The screenshot in Firefox which is expected:
![image](https://user-images.githubusercontent.com/20729067/53845985-10a26800-3f60-11e9-878e-e6c021b0935e.png)

**Comment by denis-anisimov** [comment] 2019-03-06 08:44
Hmm.

I cannot reproduce it with the latest `Grid`  SNAPSHOT and also with `Grid` 1.2 SNAPSHOT.
Could you please try the latest `13.0.0`  platform?

Also : if you still have an issue with `12.0.7` then we will need the exact versions of everything you use.
It's `Grid`  version , date picker  version.
Exact Chrome version, OS version.

The easiest way to provide info about component versions is to use https://github.com/vaadin/skeleton-starter-flow as a base, modify it to provide a usecase and attach it to the ticket.
We will be able to find out `Grid` and date picker versions from there.
But we will still need Chrome version  and your OS version.

**Comment by firestormdong** [comment] 2019-03-06 20:50
All the components I used are the versions referenced in vaadin-core:12.0.7
Grid: vaadin-grid:5.2.5 vaadin-grid-flow:2.1.5
DatePicker: vaadin-date-picker:3.3.2 vaadin-date-picker-flow:1.2.3

Chrome: Version 72.0.3626.119 (Official Build) (64-bit)
OS: Windows 10 Enterprise Version 1803 (OS Build 17134.590)

I'll try the versions you mentioned.

**Comment by firestormdong** [comment] 2019-03-06 21:19
Attached the project based on skeleton-starter-flow-12: [skeleton-starter-flow-12.zip](https://github.com/vaadin/vaadin-grid-flow/files/2938321/skeleton-starter-flow-12.zip)

Just found that the first time opening the page in Chrome do work well.
To reproduce the issue, you need to refresh the page (F5 or Ctrl+R).

**Comment by firestormdong** [comment] 2019-03-06 21:25
And I just tested in Vaadin 13.0.0, this issue is also reproducible.

**Comment by firestormdong** [comment] 2019-04-02 20:30
Any update to this?

**Comment by web-padawan** [comment] 2020-05-20 13:49
This appears to be the same as vaadin/flow#5025 (Chrome regression, now fixed). Closing.

**Closed by web-padawan** 2020-05-20 13:49 UTC
Labels: waiting for author
