### ISSUE TITLE
Slow Grid Scrolling on Huawei Mate 10 Pro

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-grid-flow#478] opened 2019-01-14 09:05 UTC
Moved from V8 github repo : https://github.com/vaadin/framework/issues/11393

The Grid scroling is very jerky and slow some phones e.g. huawei mate 10 pro.
i can't find the reason why. it's faster on some lower specc huawei phones.
both using chrome browser.

Vaadin Framework Grid 5.2.5

- Browser version
Chrome V71.0.3578.99

- Expected behavior
Smooth Scrolling

- Actual behavior
Slow scrolling even after all data is loaded.

**Comment by web-padawan** [comment] 2019-02-04 11:14
Note that latest Chrome, Safari and Firefox all support the Web Components natively (Custom Elements and Shadow DOM), and therefore the experience should be much better nowadays, and Edge has recently announced moving to Chromium.

Also, we aim to provide ES modules and Polymer 3 support in the next Vaadin platform LTS version 14 in order to get rid of the HTML Imports polyfill (which still slows things down a bit).

We do realise your concerns and importance of the scrolling issue, though. So we are going to iterate on the possible low-hanging fruit regarding the performance improvements.

Let me this as duplicate of vaadin/vaadin-grid#1518 and vaadin/vaadin-grid#1249 and continue there.

**Closed by web-padawan** 2019-02-04 11:14 UTC
