### ISSUE TITLE
Resizing of details view

### ISSUE THREAD

**Issue by robert-lee-hisl** [vaadin/vaadin-grid-flow#793] opened 2019-10-17 12:06 UTC
I am unsure if this is a bug or a feature request. It may be a duplicate of https://github.com/vaadin/vaadin-grid-flow/issues/677

The attached replicates the issue: [gridbug.txt](https://github.com/vaadin/vaadin-grid-flow/files/3739048/gridbug.txt)

If the size of the details view changes, there appears to be no way to update the grid to reflect the new size. refreshItem() or refreshAll() have no effect; I haven't tried refreshItem() while forcing the original item to change.

The best workaround I've found is to hide the details view, then re-show it again in another call to the server, but this causes visual flicker. (This does nothing if run in the same call).

**Comment by tomivirkki** [comment] 2019-10-17 12:16
Hi, there's no public Java API for this unfortunately. You can try invoking the Web Component's [`notifyResize()`](https://cdn.vaadin.com/vaadin-grid/5.4.11/#/elements/vaadin-grid#method-notifyResize) API with `grid.getElement().executeJs("this.notifyResize()");`

**Comment by robert-lee-hisl** [comment] 2019-10-17 13:10
@tomivirkki this works and avoids the flicker problem, although the item details seems to partially overlap some of its grid row in some cases.

**Comment by tomivirkki** [comment] 2019-10-17 13:30
Sounds like something still changes size after `notifyResize` is called. You can try deferring it with requestAnimationFrame:
```java
grid.getElement().executeJs(
  "requestAnimationFrame(function() { $0.notifyResize() })",
  grid.getElement());
```
If there are images in the details content, you'll need to [set their size beforehand](https://github.com/vaadin/vaadin-combo-box/issues/843#issuecomment-540494837).

**Comment by robert-lee-hisl** [comment] 2019-10-17 15:50
@tomivirkki Thank you for the update. I think I spoke too soon, as I applied the code to one grid but tested another. The original workaround is now working for me.
I'm still not sure if this is a bug or a feature request, but I would expect the grid to be able to determine if the size of an open item details renderer had changed somehow and take action.

**Comment by web-padawan** [comment] 2020-02-20 18:02
Closing as duplicate of #677.

**Closed by web-padawan** 2020-02-20 18:02 UTC
