### ISSUE TITLE
TextField loses focus after pressing enter (only in header row)

### ISSUE THREAD

**Issue by philippsaxess** [vaadin/vaadin-grid-flow#1122] opened 2020-09-23 05:57 UTC
The behavior can be reproduced in [vaadin-grid-example](https://vaadin.com/components/vaadin-grid/java-examples/filtering).
TextField's outside the grid behave differently - the focus remains **as expected** in the field.

Steps to reproduce:

- Insert TextField-Filter into header (or open  [vaadin-grid-example](https://vaadin.com/components/vaadin-grid/java-examples/filtering))
- Input text
- Press "enter"
- -> HeaderCell is focused -> TextField loses focus -> Further text input is no longer possible

![MicrosoftTeams-image](https://user-images.githubusercontent.com/60783069/94020779-99d3f680-fdb3-11ea-81da-a74e3871d137.png)

**Comment by TatuLund** [comment] 2020-09-23 14:04
This is perhaps related to this issue https://github.com/vaadin/vaadin-control-state-mixin/issues/50

**Comment by web-padawan** [comment] 2020-10-06 07:47
The problem in the demo is related to the fact that `TextField` used for filtering does not have `focus-target` attribute.

This is how the updated code snippet should look like:

```
// First filter
TextField firstNameField = new TextField();
firstNameField.getElement().setAttribute("focus-target", "true");
```

Then <kbd>Enter</kbd> would toggle editing for this text-field and will not lose focus to the containing cell.

**Comment by web-padawan** [comment] 2020-10-06 08:26
Submitted https://github.com/vaadin/vaadin-grid-flow/pull/1135. Only the demo is fixed, the component itself works as intended.

**Comment by web-padawan** [comment] 2020-10-06 11:45
Closing this as working as intended. There will be another release for Vaadin 14.4 with a demo update later on.
Updating [GridFlow examples](https://vaadin.com/components/vaadin-grid/java-examples/filtering) will take some time, and will be done once 14.4.1 is out (probably next week).

**Closed by web-padawan** 2020-10-06 11:45 UTC
Labels: BFP, Impact: High, Severity: Minor, bug
