### ISSUE TITLE
TreeGrid doesnt handle expand after refresh the page

### ISSUE THREAD

**Issue by TheSilentHorizon** [vaadin/vaadin-grid-flow#1113] opened 2020-09-06 16:22 UTC
### Description

When you have a TreeGrid (Selection Type doesnt matter, i tested it) and your RouterLayout has @PreserveOnRefresh as annotation included, then the following is happening:

My page with the TreeGrid is calling:

```
List<CategoryDetails> parentPath = walkToRoot(categoryDetails);
expand(parentPath);
```
to expand the TreeGrid to the selected item.
When you are going on the page first, this behaviour does work as expected. But if you refresh the page (by pressing F5 e.g.) the expand method gets called and gets the correct path to open **but does not trigger the UI**.

This means that something JS relevant doesnt work on restart with @PreserveOnRefresh being active.

### How to recreate

Just create a page with a TreeGrid, some Items and @PreserveOnRefresh enabled. On SetParameter or AfterNavigation, trigger the expand method of the TreeGrid for it, and restart it. Maybe i can create a working example in my freetime...

No JS Error in Debug Mode, so its just not working.

### Additional Information

```
OS: Windows 10, 2004
Vaadin: 16.0.3
Spring Boot: 2.3.3 Release
JDK: Adopt OpenJDK 14.0.2
Browser: Latest Chrome
```

**Comment by tomivirkki** [comment] 2020-09-08 11:05
Thank you for reporting. Closing as a dupe of #1088

**Closed by tomivirkki** 2020-09-08 11:05 UTC
